# Generated by Django 6.0.2 on 2026-06-06 15:35

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sfap", "0005_batch_breederflock_dailyobservation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Feed Name"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Acha wazi kama limetengenezwa shambani.",
                        max_length=100,
                        verbose_name="Brand/Manufacturer",
                    ),
                ),
                (
                    "feed_source",
                    models.CharField(
                        choices=[
                            ("FARM_PRODUCED", "Kiasili / Limeshindwa Shambani"),
                            ("COMMERCIAL", "Kibiashara / Kununuliwa"),
                        ],
                        default="FARM_PRODUCED",
                        max_length=20,
                        verbose_name="Feed Source",
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores vitamins, proteins, and mineral percentages.",
                        verbose_name="Nutritional Composition",
                    ),
                ),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Unit Price (per KG)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Type",
                "verbose_name_plural": "Feed Types",
                "db_table": "feed_type",
            },
        ),
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "total_quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Stock (KG)",
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Triggers an alert when stock falls below this amount.",
                        max_digits=10,
                        verbose_name="Reorder Level (KG)",
                    ),
                ),
                (
                    "stock_logs",
                    models.JSONField(
                        default=list,
                        help_text="Audit trail of feed arrivals and batch-specific metadata.",
                        verbose_name="Stock Logs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="fns.feedtype",
                        verbose_name="Feed Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Inventory",
                "verbose_name_plural": "Feed Inventories",
                "db_table": "feed_inventory",
            },
        ),
        migrations.CreateModel(
            name="FeedConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "quantity_used_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantity Used (KG)",
                    ),
                ),
                (
                    "waste_amount_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Waste Amount (KG)",
                    ),
                ),
                (
                    "water_liters_added",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Water Intake (Liters)",
                    ),
                ),
                (
                    "consumption_notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores waste data, feeder status, and behavioral observations.",
                        verbose_name="Consumption Notes",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_logs",
                        to="sfap.batch",
                        verbose_name="Flock Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fns.feedtype",
                        verbose_name="Feed Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Consumption Log",
                "db_table": "feed_consumption",
                "ordering": ["-created_on"],
                "permissions": [
                    ("update_water_intake", "Can update water intake"),
                    ("view_kpi_dashboard", "Can view KPI dashboard"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="feedtype",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["composition"], name="feed_composition_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedinventory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["stock_logs"], name="feed_stock_log_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["consumption_notes"], name="feed_usage_notes_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedconsumption",
            unique_together={("batch", "created_on", "feed_type")},
        ),
    ]
