# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.utils.timezone
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "quantity_used_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantity Used (KG)",
                    ),
                ),
                (
                    "waste_amount_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Waste Amount (KG)",
                    ),
                ),
                (
                    "water_liters_added",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Water Intake (Liters)",
                    ),
                ),
                (
                    "consumption_notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores waste data, feeder status, and behavioral observations.",
                        verbose_name="Consumption Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Consumption Log",
                "db_table": "feed_consumption",
                "ordering": ["-created_on"],
                "permissions": [
                    ("update_water_intake", "Can update water intake"),
                    ("view_kpi_dashboard", "Can view KPI dashboard"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "total_quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Stock (KG)",
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Triggers an alert when stock falls below this amount.",
                        max_digits=10,
                        verbose_name="Reorder Level (KG)",
                    ),
                ),
                (
                    "stock_logs",
                    models.JSONField(
                        default=list,
                        help_text="Audit trail of feed arrivals and batch-specific metadata.",
                        verbose_name="Stock Logs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Inventory",
                "verbose_name_plural": "Feed Inventories",
                "db_table": "feed_inventory",
            },
        ),
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Feed Name"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Acha wazi kama limetengenezwa shambani.",
                        max_length=100,
                        verbose_name="Brand/Manufacturer",
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores vitamins, proteins, and mineral percentages.",
                        verbose_name="Nutritional Composition",
                    ),
                ),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Unit Price (per KG)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Type",
                "verbose_name_plural": "Feed Types",
                "db_table": "feed_type",
            },
        ),
    ]
