# Generated by Django 6.0.2 on 2026-06-20 20:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0001_initial"),
        ("fns", "0001_initial"),
        ("sfap", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedconsumption",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_logs",
                to="sfap.batch",
                verbose_name="Flock Batch",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedtype",
            name="feed_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="config.feedsourcechoices",
            ),
        ),
        migrations.AddField(
            model_name="feedtype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="feed_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="fns.feedtype",
                verbose_name="Feed Type",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="feed_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fns.feedtype",
                verbose_name="Feed Type",
            ),
        ),
        migrations.AddIndex(
            model_name="feedtype",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["composition"], name="feed_composition_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedinventory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["stock_logs"], name="feed_stock_log_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["consumption_notes"], name="feed_usage_notes_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedconsumption",
            unique_together={("batch", "created_on", "feed_type")},
        ),
    ]
