# Generated by Django 6.0.2 on 2026-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fns", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconsumption",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="feedinventory",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="feedtype",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
    ]
