# Generated by Django 6.0.2 on 2026-04-14 07:38

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fns", "0002_feedinventory"),
        ("sfap", "0017_alter_medicalrecord_date_of_administration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "quantity_used_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantity Used (KG)",
                    ),
                ),
                (
                    "consumption_notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores waste data, feeder status, and behavioral observations.",
                        verbose_name="Consumption Notes",
                    ),
                ),
                (
                    "waste_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_logs",
                        to="sfap.batch",
                        verbose_name="Flock Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fns.feedtype",
                        verbose_name="Feed Type",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Consumption Log",
                "db_table": "feed_consumption",
                "ordering": ["-created_on"],
                "permissions": [
                    ("update_water_intake", "Can update water intake"),
                    ("view_kpi_dashboard", "Can view KPI dashboard"),
                ],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["consumption_notes"], name="feed_usage_notes_gin_idx"
                    )
                ],
                "unique_together": {("batch", "created_on", "feed_type")},
            },
        ),
    ]
