# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeIDSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., HR, MFG, SLS",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Employee ID Sequence",
                "verbose_name_plural": "Employee ID Sequences",
                "db_table": "employee_id_sequence",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Department name"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Department Description"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique short code for ID generation (e.g., HR, MFG, SLS, MKT)",
                        max_length=10,
                        unique=True,
                        verbose_name="Department Code",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hrms.department",
                        verbose_name="Minor department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "department",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Employee Number",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                        ],
                        db_index=True,
                        default="SINGLE",
                        max_length=20,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "health_clearance_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Required for Processing Plant staff. Must be renewed annually.",
                        null=True,
                        verbose_name="Health Clearance Expiry",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer Not to Say"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Employee Gender",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Hire Date")),
                (
                    "base_salary_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "base_salary",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, verbose_name="Base Salary"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this instead of deleting the employee for audit history.",
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "hr_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores emergency contacts, ID numbers, skills, and payroll configurations.",
                        verbose_name="HR Metadata",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="hrms.department",
                        verbose_name="Employee Department",
                    ),
                ),
                (
                    "employee_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="status",
                        to="config.usertitle",
                        verbose_name="Employee Title",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Determines benefits eligibility; e.g., Casuals usually don't get housing.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="employee_type",
                        to="config.employmenttype",
                        verbose_name="Employement Type",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hrms.employee",
                        verbose_name="Reports To",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employee",
                "ordering": ["employee_number"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["hr_metadata"], name="emp_hr_meta_gin_idx"
                    )
                ],
            },
        ),
    ]
