# Generated by Django 6.0.2 on 2026-05-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
    ]
