# Generated by Django 6.0.2 on 2026-05-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0001_initial"),
        ("ppms", "0001_initial"),
        ("sfap", "0007_incubator_incubationcycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="assigned_plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workers",
                to="ppms.processingplant",
                verbose_name="Assigned Processing Plant",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="assigned_shed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workers",
                to="sfap.farmshed",
                verbose_name="Assigned Shed",
            ),
        ),
    ]
