# Generated by Django 6.0.2 on 2026-05-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_employee_assigned_plant_employee_assigned_shed"),
        ("sfap", "0015_cropproduction_ecologicalinput"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="assigned_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_block",
                to="sfap.farmblock",
                verbose_name="Assigned Block",
            ),
        ),
    ]
