# Generated by Django 6.0.2 on 2026-06-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_employee"),
        ("ppms", "0002_processingsession"),
        ("sfap", "0005_batch_breederflock_dailyobservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="assigned_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_block",
                to="sfap.farmblock",
                verbose_name="Assigned Block",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="assigned_plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workers",
                to="ppms.processingplant",
                verbose_name="Assigned Processing Plant",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="assigned_shed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workers",
                to="sfap.farmshed",
                verbose_name="Assigned Shed",
            ),
        ),
    ]
