# Generated by Django 6.0.2 on 2026-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_alter_department_updated_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeIDSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., HR, MFG, SLS",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Employee ID Sequence",
                "verbose_name_plural": "Employee ID Sequences",
                "db_table": "employee_id_sequence",
            },
        ),
    ]
