"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import config
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Enterprise Apps
    "core",
    # "hrms",
    # "lrh",
    # "sfap",
    # "ppms",
    # "fns",
    # "ipms",

    # third part packages
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "guardian",
    "drf_spectacular",
    "django.contrib.humanize",
    "corsheaders",
    "mptt",
    "djmoney",
    "djmoney.contrib.exchange",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "utils.AuthActivityMiddleware",
    'common.middleware.EnterpriseUserPreferenceMiddleware',
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:6581",
    "http://localhost:11708",
]

FRONTEND_URL = "http://localhost:4200"
# FRONTEND_URL = "" # Production url

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "common.permissions.security.EnterpriseEmailOrPhoneAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Dar_es_Salaam"

USE_I18N = True

USE_TZ = True

USE_L10N = True

LANGUAGES = [
    ("en-us", _("English (US)")),
    ("en-gb", _("English (British)")),
    ("sw", _("Kiswahili")),
    ('fr', _('French')),
    ("zh-hans", _("Simplified Chinese")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale/"
]

# Django-money settings
CURRENCIES = ("TZS", "USD", "KES", "EUR")

CURRENCY_CHOICES = [
    ("TZS", "Tanzanian Shilling"),
    ("USD", "US Dollar"),
    ("KES", "Kenyan Shilling"),
    ("EUR", "Euro"),
]

DEFAULT_CURRENCY = "TZS"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

AUTH_USER_MODEL = "core.User"

PHONENUMBER_DEFAULT_REGION = "TZ"

DEFAULT_CURRENCY = "TZS"

OTP_CODE_LENGTH = 6

OTP_EXPIRATION_TIME = 300  # 5 minutes OTP expiry time

EMAIL_TIMEOUT = 15

PASSWORD_RESET_TIMEOUT = 7200  # 2 hours in seconds

MEDIA_ROOT = BASE_DIR / ""

MEDIA_URL = "Media/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    'DEFAULT_PERMISSION_CLASSES': [
       'rest_framework.permissions.AllowAny',
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend", "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter"),
    "EXCEPTION_HANDLER": "common.exceptions.general_exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "common.renderers.GeneralEntepriseJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "otp_attempt": "3/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "UPDATE_LAST_LOGIN": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_CLAIM": "user_id",
    "USER_ID_FIELD": "email",  # email as the main identifier
}

SPECTACULAR_SETTINGS = {
    # 'TITLE': 'Ilagavye Enterprise API Documentation, Hospitality Makes Life Better',
    # 'DESCRIPTION': 'The well documented API Scheme for Ilagavye Enterprise',
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # "SCHEMA_PATH_PREFIX": "/api/iv1/",
    "COMPONENT_SPLIT_PATCH": True,
    "COMPONENT_SPLIT_REQUEST": True,
}

# Email Configuration
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = EMAIL_PORT = config("EMAIL_PORT")
EMAIL_USE_TLS = config("EMAIL_USE_TLS")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
DEFAULT_FROM_EMAIL = "Ilagavye Enterprise <ale.compuny2020@gmail.com>"
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
