# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import common.services.file_management
import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="First Name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Staff Status"),
                ),
                (
                    "is_default_password",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for staff; forced password change required if True.",
                        verbose_name="Using Default Password",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email/phone via OTP.",
                        verbose_name="Identity Verified",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_profile_complete",
                    models.BooleanField(
                        default=False,
                        help_text="True if the user has filled in all required HR/KYC metadata.",
                        verbose_name="Profile Complete",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="User's photo for visual identification on Kiosks and reports.",
                        null=True,
                        upload_to=common.services.file_management.upload_profile_picture,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            common.validators.MimeTypeValidator(
                                ["image/jpg", "image/jpeg", "image/png"]
                            ),
                        ],
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "status_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed audit data for verification and profile completion stages.",
                        verbose_name="Status Metadata",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "System Users",
                "db_table": "user",
                "permissions": [
                    ("can_register_staff", "Can register a new staff user"),
                    (
                        "can_reset_password_other_user",
                        "Can force reset any user's password",
                    ),
                    (
                        "can_deactivate_user",
                        "Can deactivate any user account (is_active = False)",
                    ),
                    ("can_toggle_is_staff", "Can change a user's is_staff status"),
                    ("can_change_self_password", "Can reset individual password"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="OTP Code")),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="Expires At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("LOGIN", "Login"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("TRANSACTION_AUTH", "Transaction Authorization"),
                            ("EMAIL_CHANGE", "Email Change Verification"),
                            ("PHONE_VERIFICATION", "Phone Number Verification"),
                            ("2FA_ENABLE", "Two-Factor Auth Enablement"),
                            ("ACCOUNT_DELETION", "Account Deletion Confirmation"),
                            ("STAFF_INVITATION", "Staff Onboarding Invitation"),
                        ],
                        max_length=20,
                        verbose_name="Token Type",
                    ),
                ),
                (
                    "is_link_based",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this record represents an email-based secure link.",
                        verbose_name="Is Link Based",
                    ),
                ),
                (
                    "otp_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores security audit data like attempt counts and delivery logs.",
                        verbose_name="OTP Metadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Token",
                "verbose_name_plural": "OTP Tokens",
                "db_table": "otp",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
                ("street_address", models.TextField(verbose_name="Street Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="State/Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "address_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_types",
                        to="config.addresstype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "user_address",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Flexible JSON object storing user preferences.",
                        verbose_name="Preferences",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preference",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["status_metadata"], name="status_metadata_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useraddress",
            unique_together={("user", "address_type")},
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["preferences"], name="preferences_gin_idx"
            ),
        ),
    ]
