# Generated by Django 6.0.2 on 2026-04-19 05:44

import common.services.file_management
import common.validators
import django.contrib.postgres.indexes
import django.core.validators
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="First Name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Staff Status"),
                ),
                (
                    "is_default_password",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for staff; forced password change required if True.",
                        verbose_name="Using Default Password",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email/phone via OTP.",
                        verbose_name="Identity Verified",
                    ),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(
                        default=False,
                        help_text="True if the user has filled in all required HR/KYC metadata.",
                        verbose_name="Profile Complete",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="User's photo for visual identification on Kiosks and reports.",
                        null=True,
                        upload_to=common.services.file_management.upload_profile_picture,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            common.validators.MimeTypeValidator(
                                ["image/jpg", "image/jpeg", "image/png"]
                            ),
                        ],
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "status_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed audit data for verification and profile completion stages.",
                        verbose_name="Status Metadata",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "System Users",
                "db_table": "user",
                "permissions": [
                    ("can_register_staff", "Can register a new staff user"),
                    (
                        "can_reset_password_other_user",
                        "Can force reset any user's password",
                    ),
                    (
                        "can_deactivate_user",
                        "Can deactivate any user account (is_active = False)",
                    ),
                    ("can_toggle_is_staff", "Can change a user's is_staff status"),
                    ("can_change_self_password", "Can reset individual password"),
                ],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["status_metadata"], name="status_metadata_gin_idx"
                    )
                ],
            },
        ),
    ]
