# Generated by Django 6.0.2 on 2026-06-07 12:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="OTP Code")),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="Expires At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("LOGIN", "Login"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("TRANSACTION_AUTH", "Transaction Authorization"),
                            ("EMAIL_CHANGE", "Email Change Verification"),
                            ("PHONE_VERIFICATION", "Phone Number Verification"),
                            ("2FA_ENABLE", "Two-Factor Auth Enablement"),
                            ("ACCOUNT_DELETION", "Account Deletion Confirmation"),
                            ("STAFF_INVITATION", "Staff Onboarding Invitation"),
                        ],
                        max_length=20,
                        verbose_name="Token Type",
                    ),
                ),
                (
                    "is_link_based",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this record represents an email-based secure link.",
                        verbose_name="Is Link Based",
                    ),
                ),
                (
                    "otp_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores security audit data like attempt counts and delivery logs.",
                        verbose_name="OTP Metadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Token",
                "verbose_name_plural": "OTP Tokens",
                "db_table": "otp",
                "ordering": ["-created_at"],
            },
        ),
    ]
