# Generated by Django 6.0.2 on 2026-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_link_based",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this record represents an email-based secure link.",
                verbose_name="Is Link Based",
            ),
        ),
    ]
