# Generated by Django 6.0.2 on 2026-06-07 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address/Location Type",
                "verbose_name_plural": "Address/Location Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Structural Corporate Asset Type",
                "verbose_name_plural": "Fixed Structural Corporate Asset Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BirdType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avian Bird Classification Type",
                "verbose_name_plural": "Avian Bird Classification Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarrierType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportation Carrier Type",
                "verbose_name_plural": "Transportation Carrier Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Currency Transaction ISO Code",
                "verbose_name_plural": "Financial Currency Transaction ISO Codes",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Market Classification Segment",
                "verbose_name_plural": "Customer Market Classification Segments",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiseaseOutbreakStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Epidemiological Outbreak Status",
                "verbose_name_plural": "Epidemiological Outbreak Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment Classification Type",
                "verbose_name_plural": "Employment Classification Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventBookingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitality Event Reservation Status",
                "verbose_name_plural": "Hospitality Event Reservation Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FarmBlockStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agricultural Farm Block Rest Status",
                "verbose_name_plural": "Agricultural Farm Block Rest Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FatLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primal Meat Lipid/Fat Quality Grading Level",
                "verbose_name_plural": "Primal Meat Lipid/Fat Quality Grading Levels",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlockBatchStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch Production Status",
                "verbose_name_plural": "Flock Batch Production Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthRecordType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Health Intervention Record Type",
                "verbose_name_plural": "Clinical Health Intervention Record Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdentityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Type Documentation",
                "verbose_name_plural": "Identity Type Documentations",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncubationCycleStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubation Cycle Step Status",
                "verbose_name_plural": "Incubation Cycle Step Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncubatorMachineType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubator Machine Configuration Type",
                "verbose_name_plural": "Incubator Machine Configuration Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemDisposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Item Return Disposition",
                "verbose_name_plural": "Customer Item Return Dispositions",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeatCutType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carcass Commercial Meat Cut Selection",
                "verbose_name_plural": "Carcass Commercial Meat Cut Selections",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Status Definition",
                "verbose_name_plural": "Order Status Definitions",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PackageStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Warehouse Inventory Status",
                "verbose_name_plural": "Package Warehouse Inventory Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Payment Channel Settlement Method",
                "verbose_name_plural": "Accounting Payment Channel Settlement Methods",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Product Category",
                "verbose_name_plural": "Inventory Product Categories",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agronomy Crop Production Status",
                "verbose_name_plural": "Agronomy Crop Production Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RateType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logistics Valuation Service Rate Billing Type",
                "verbose_name_plural": "Logistics Valuation Service Rate Billing Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistrationStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Status",
                "verbose_name_plural": "Registration Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalUnitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Housing Property Unit Grid Type",
                "verbose_name_plural": "Commercial Housing Property Unit Grid Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SaleInvoiceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Sales Invoice Accounting Status",
                "verbose_name_plural": "Commercial Sales Invoice Accounting Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShippingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping/Logistics Status",
                "verbose_name_plural": "Shipping/Logistics Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Procurement Origin Source",
                "verbose_name_plural": "Resource Procurement Origin Sources",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeciesType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Biological Species Type",
                "verbose_name_plural": "Animal Biological Species Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovementType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction Movement Type",
                "verbose_name_plural": "Stock Transaction Movement Types",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockReadinessStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Market Readiness Status",
                "verbose_name_plural": "Stock Market Readiness Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thermal Preservation Storage State",
                "verbose_name_plural": "Thermal Preservation Storage States",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageUnitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Unit Infrastructure Placement",
                "verbose_name_plural": "Storage Unit Infrastructure Placements",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskPriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Facility Task Execution Priority",
                "verbose_name_plural": "Operational Facility Task Execution Priorities",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Task/Support Ticket Lifecycle Status",
                "verbose_name_plural": "Operational Task/Support Ticket Lifecycle Statuses",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Standardized Unit of Measure (UOM)",
                "verbose_name_plural": "Inventory Standardized Units of Measure (UOM)",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserTitle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Title",
                "verbose_name_plural": "User Titles",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WasteDisposalMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bio-Waste Management Disposal Method",
                "verbose_name_plural": "Bio-Waste Management Disposal Methods",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BreedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeds",
                        to="core.speciestype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Genetic Breed Variant",
                "verbose_name_plural": "Animal Genetic Breed Variants",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
