# Generated by Django 6.0.2 on 2026-06-12 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_addresstype_table_alter_assettype_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
                ("street_address", models.TextField(verbose_name="Street Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="State/Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "address_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_types",
                        to="core.addresstype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "user_address",
                "unique_together": {("user", "address_type")},
            },
        ),
    ]
