# Generated by Django 6.0.2 on 2026-06-17 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmVehicleType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Vehicle Type",
                "verbose_name_plural": "Farm Vehicle Types",
                "db_table": "farm_vehicle_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
