# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0001_initial"),
        ("ipss", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "contact_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "customer_profile",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Profile Metadata"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Credit Limit",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.customertype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "db_table": "customer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                ("reason", models.TextField()),
                ("is_redeemed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="srs.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_credit_note",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "subtotal_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=15, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=djmoney.money.Money(0, "TZS"),
                        max_digits=15,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "total_payable_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_payable",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=15, verbose_name="Total Payable"
                    ),
                ),
                (
                    "internal_notes",
                    models.JSONField(default=list, verbose_name="Order History Log"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offline_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_orders",
                        to="srs.customer",
                    ),
                ),
                (
                    "online_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onlineline_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.orderstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order",
                "db_table": "sales_order",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantity Sold",
                    ),
                ),
                (
                    "pricing_snapshot",
                    models.JSONField(default=dict, verbose_name="Pricing Snapshot"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="srs.order",
                    ),
                ),
                (
                    "packaged_product",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ipss.packagedproduct",
                    ),
                ),
                (
                    "product_stock",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ipss.productstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "db_table": "sales_item",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentage"), ("FIXED", "Fixed Amount")],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("rules", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promotion",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("sales_type", models.CharField(default="direct", max_length=30)),
                (
                    "total_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Sale Metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_record",
                        to="srs.order",
                    ),
                ),
                (
                    "sales_outlet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_sales",
                        to="ipss.storageunit",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.saleinvoicestatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sale_transaction",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_paid", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.paymentmethod",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="srs.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "discount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "line_total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "line_total",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Product Attributes at Sale",
                    ),
                ),
                (
                    "item_disposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.itemdisposition",
                    ),
                ),
                (
                    "packaged_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ipss.packagedproduct",
                    ),
                ),
                (
                    "product_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipss.productstock",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="srs.sale",
                    ),
                ),
                (
                    "unit_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "sale_item",
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="{'restock_warehouse_id': 1, 'refund_transaction_id': '...', 'approved_by': 'Manager'}",
                    ),
                ),
                (
                    "disposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.itemdisposition",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="srs.sale",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="srs.saleitem"
                    ),
                ),
            ],
            options={
                "db_table": "return_request",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["customer_profile"], name="customer_profile_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="metadata_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["internal_notes"], name="sales_order_notes_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["pricing_snapshot"], name="order_item_price_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["sales_outlet", "created_on"],
                name="sale_transa_sales_o_2995cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["created_by"], name="sale_transa_created_d91176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="sales_metadata_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["attributes"], name="attributes_gin_idx"
            ),
        ),
    ]
