# Generated by Django 6.0.2 on 2026-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
    ]
