# Generated by Django 6.0.2 on 2026-06-06 16:18

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipss", "0001_initial"),
        ("srs", "0002_order_orderitem_order_sales_order_notes_gin_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("sales_type", models.CharField(default="direct", max_length=30)),
                (
                    "total_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            (
                                "MOBILE_MONEY",
                                "Mobile Money (M-Pesa/Tigo Pesa/Airtel Money)",
                            ),
                            ("ONLINE_WALLET", "Online Wallet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Sale Metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_record",
                        to="srs.order",
                    ),
                ),
                (
                    "sales_outlet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_sales",
                        to="ipss.storageunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sale_transaction",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "unit_measure",
                    models.CharField(
                        choices=[
                            ("TRAY", "Tray (Treya)"),
                            ("KG", "Kilogram (Kilogramu)"),
                            ("LITER", "Liter (Lita)"),
                            ("PCS", "Pieces (Idadi/Vipande)"),
                            ("BAG", "Bag (Mfuko)"),
                            ("BOX", "Box (Boxi)"),
                        ],
                        default="pc",
                        max_length=50,
                    ),
                ),
                (
                    "discount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "line_total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "line_total",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=15),
                ),
                (
                    "item_disposition",
                    models.CharField(
                        choices=[
                            ("SOLD", "Successfully Sold"),
                            ("RETURNED", "Returned by Customer"),
                            ("CHANGED", "Exchanged for Different Product"),
                            ("DAMAGED", "Damaged/Defective (Pre-delivery)"),
                            ("REFUND_ISSUED", "Item Refunded"),
                        ],
                        default="SOLD",
                        max_length=20,
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Product Attributes at Sale",
                    ),
                ),
                (
                    "packaged_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ipss.packagedproduct",
                    ),
                ),
                (
                    "product_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipss.productstock",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="srs.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sale_item",
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["sales_outlet", "created_on"],
                name="sale_transa_sales_o_2995cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["created_by"], name="sale_transa_created_d91176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="sales_metadata_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["attributes"], name="attributes_gin_idx"
            ),
        ),
    ]
