# Generated by Django 6.0.2 on 2026-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0003_sale_saleitem_sale_sale_transa_sales_o_2995cb_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="payment_method",
        ),
    ]
