# Generated by Django 6.0.2 on 2026-04-11 18:33

import django.core.validators
import helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lrh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeregistrationhistory",
            name="contract_document",
            field=models.FileField(
                blank=True,
                help_text="Upload the signed employment contract (PDF/JPG).",
                null=True,
                upload_to=helpers.validators.upload_employee_contract_document,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    helpers.validators.MimeTypeValidator(["application/pdf"]),
                ],
            ),
        ),
    ]
