# Generated by Django 6.0.2 on 2026-06-06 15:35

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sfap", "0005_batch_breederflock_dailyobservation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposalArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Location name"
                    ),
                ),
                (
                    "disposal_metadata",
                    models.JSONField(default=dict, verbose_name="Disposal Metadata"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposal Area",
                "verbose_name_plural": "Disposal Areas",
                "db_table": "disposal_area",
            },
        ),
        migrations.CreateModel(
            name="WasteCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Waste Type Name"
                    ),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("INCINERATION", "Incineration"),
                            ("COMPOSTING", "Composting"),
                            ("SALE", "Sale to Third Party"),
                            ("LANDFILL", "Landfill"),
                            ("RECYCLE", "Recycling"),
                        ],
                        default="RECYCLE",
                        max_length=50,
                        verbose_name="Primary Disposal Method",
                    ),
                ),
                (
                    "financial_logic",
                    models.JSONField(
                        default=dict,
                        help_text="Stores pricing for sales or costs for disposal per unit.",
                        verbose_name="Financial Logic",
                    ),
                ),
                (
                    "requires_special_handling",
                    models.BooleanField(
                        default=False,
                        help_text="If true, requires specific safety protocols for collection.",
                        verbose_name="Hazardous / Special Handling",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Category",
                "verbose_name_plural": "Waste Categories",
                "db_table": "waste_category",
            },
        ),
        migrations.CreateModel(
            name="WasteCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Quantity (KG)"
                    ),
                ),
                (
                    "collection_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores physical properties and audit data from the point of collection.",
                        verbose_name="Collection Metadata",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wces.wastecategory",
                        verbose_name="Waste Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_collections",
                        to="sfap.farm",
                        verbose_name="Farm Location",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_produced",
                        to="sfap.batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Collection Log",
                "db_table": "waste_colleaction",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="WasteOutflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Total Outflow Weight (KG)",
                    ),
                ),
                (
                    "exit_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Tracks transport costs, sale revenue, and buyer/logistics info.",
                        verbose_name="Exit Audit Metadata",
                    ),
                ),
                (
                    "collection_logs",
                    models.ManyToManyField(
                        related_name="outflows",
                        to="wces.wastecollection",
                        verbose_name="Linked Collections",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="wces.disposalarea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Outflow Audit",
                "db_table": "waste_audit",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddIndex(
            model_name="disposalarea",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["disposal_metadata"], name="disposal_metadata_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wastecategory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["financial_logic"], name="waste_fin_logic_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wastecollection",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["collection_details"], name="waste_coll_meta_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wasteoutflow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["exit_metadata"], name="waste_exit_meta_gin_idx"
            ),
        ),
    ]
