# Generated by Django 6.0.2 on 2026-04-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Supplier", "verbose_name_plural": "Suppliers"},
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="supplier",
        ),
    ]
