from django.utils.translation import gettext_lazy as _

LOOKUP_SEED_DATA = {
    "RegistrationStatus": [
        {"code": "PENDING", "name": "Pending Verification", "color_hex": "#F39C12", "sort_order": 1},
        {"code": "VERIFIED", "name": "Verified & Approved", "color_hex": "#2ECC71", "sort_order": 2},
        {"code": "REJECTED", "name": "Rejected/Incomplete", "color_hex": "#E74C3C", "sort_order": 3},
        {"code": "REVOKED", "name": "Revoked/Terminated", "color_hex": "#7F8C8D", "sort_order": 4},
    ],
    "UserTitle": [
        {"code": "MR", "name": "Mr.", "sort_order": 1},
        {"code": "MRS", "name": "Mrs.", "sort_order": 2},
        {"code": "MS", "name": "Ms.", "sort_order": 3},
        {"code": "MISS", "name": "Miss", "sort_order": 4},
        {"code": "DR", "name": "Dr.", "sort_order": 5},
        {"code": "PROF", "name": "Prof.", "sort_order": 6},
        {"code": "ENG", "name": "Eng.", "sort_order": 7},
        {"code": "ARCH", "name": "Arch.", "sort_order": 8},
        {"code": "ADV", "name": "Adv.", "sort_order": 9},
        {"code": "CPA", "name": "CPA", "sort_order": 10},
        {"code": "VET", "name": "Vet.", "sort_order": 11},
        {"code": "PHARM", "name": "Pharm.", "sort_order": 12},
        {"code": "REV", "name": "Rev.", "sort_order": 13},
        {"code": "HON", "name": "Hon.", "sort_order": 14},
    ],
    "IdentityType": [
        {"code": "NIDA", "name": "NIDA (National ID)", "sort_order": 1},
        {"code": "PASSPORT", "name": "Passport", "sort_order": 2},
        {"code": "VOTER_ID", "name": "Voter ID", "sort_order": 3},
        {"code": "DRIVING_LICENSE", "name": "Driving License", "sort_order": 4},
    ],
    "EmploymentType": [
        {"code": "FULL_TIME", "name": "Full-Time Regular", "sort_order": 1},
        {"code": "CONTRACT", "name": "Contractor", "sort_order": 2},
        {"code": "CASUAL", "name": "Casual Laborer", "sort_order": 3},
    ],
    "AddressType": [
        {"code": "SHIPPING", "name": "Shipping", "sort_order": 1},
        {"code": "BILLING", "name": "Billing", "sort_order": 2},
        {"code": "HOME", "name": "Home", "sort_order": 3},
        {"code": "WORK", "name": "Work", "sort_order": 4},
    ],
    "OrderStatus": [
        {"code": "PENDING", "name": "Pending", "color_hex": "#F1C40F", "sort_order": 1},
        {"code": "CONFIRMED", "name": "Confirmed", "color_hex": "#3498DB", "sort_order": 2},
        {"code": "DISPATCHED", "name": "Dispatched", "color_hex": "#9B59B6", "sort_order": 3},
        {"code": "DELIVERED", "name": "Delivered", "color_hex": "#2ECC71", "sort_order": 4},
        {"code": "CANCELLED", "name": "Cancelled", "color_hex": "#E74C3C", "sort_order": 5},
    ],
    "ShippingStatus": [
        {"code": "REQUESTED", "name": "Request Received", "sort_order": 1},
        {"code": "PACKING", "name": "In Packaging", "sort_order": 2},
        {"code": "COLLECTED", "name": "Collected by Carrier", "sort_order": 3},
        {"code": "DEPARTED", "name": "Departed Facility", "sort_order": 4},
        {"code": "IN_TRANSIT", "name": "In Transit", "sort_order": 5},
        {"code": "OUT_FOR_DELIVERY", "name": "Out for Delivery", "sort_order": 6},
        {"code": "DELIVERED", "name": "Delivered", "sort_order": 7},
        {"code": "FAILED", "name": "Delivery Failed", "sort_order": 8},
    ],
    "CarrierType": [
        {"code": "INTERNAL", "name": "Farm Fleet", "sort_order": 1},
        {"code": "THIRD_PARTY", "name": "External Courier", "sort_order": 2},
        {"code": "PICKUP", "name": "Customer Pickup", "sort_order": 3},
    ],
    "StockMovementType": [
        {"code": "SALE", "name": "Sale", "sort_order": 1},
        {"code": "RETURN", "name": "Return", "sort_order": 2},
        {"code": "RESTOCK", "name": "Restock", "sort_order": 3},
        {"code": "ADJUST", "name": "Adjustment", "sort_order": 4},
        {"code": "TRANSFER", "name": "Internal Transfer", "sort_order": 5},
    ],
    "StorageUnitType": [
        {"code": "SHELF", "name": "Shelf (Rafu)", "sort_order": 1},
        {"code": "KABATI", "name": "Cabinet (Kabati)", "sort_order": 2},
        {"code": "CLIPBOARD", "name": "Clipboard", "sort_order": 3},
        {"code": "DRAWER", "name": "Drawer (Droo)", "sort_order": 4},
        {"code": "COLD_ROOM", "name": "Cold Room Rack", "sort_order": 5},
    ],
    "ItemDisposition": [
        {"code": "SOLD", "name": "Successfully Sold", "sort_order": 1},
        {"code": "RETURNED", "name": "Returned by Customer", "sort_order": 2},
        {"code": "CHANGED", "name": "Exchanged for Different Product", "sort_order": 3},
        {"code": "DAMAGED", "name": "Damaged/Defective (Pre-delivery)", "sort_order": 4},
        {"code": "REFUND_ISSUED", "name": "Item Refunded", "sort_order": 5},
    ],
    "PackageStatus": [
        {"code": "IN_STOCK", "name": "Ipo Ghalani", "sort_order": 1},
        {"code": "SOLD", "name": "Imeuzwa", "sort_order": 2},
        {"code": "SPOILED", "name": "Imeharibika/Imeoza", "sort_order": 3},
        {"code": "TRANSFERRED", "name": "Imehamishwa Banda/Ghala", "sort_order": 4},
    ],
    "SourceChoice": [
        {"code": "FARM_PRODUCED", "name": "Kiasili / Limeshindwa Shambani", "sort_order": 1},
        {"code": "COMMERCIAL", "name": "Kibiashara / Kununuliwa", "sort_order": 2},
    ],
    "ProductCategory": [
        {"code": "EGG", "name": "Eggs", "sort_order": 1},
        {"code": "MEAT", "name": "Meat/Poultry", "sort_order": 2},
        {"code": "BY_PRODUCT", "name": "By-Products (Manure/Feathers)", "sort_order": 3},
        {"code": "EQUIPMENT", "name": "Farm Equipment/Assets", "sort_order": 4},
    ],
    "BirdType": [
        {"code": "BROILER", "name": "Broiler", "sort_order": 1},
        {"code": "LAYER", "name": "Layer", "sort_order": 2},
        {"code": "KUCHI", "name": "Kuchi", "sort_order": 3},
        {"code": "LOCAL", "name": "Local", "sort_order": 4},
        {"code": "KUROILER", "name": "Kuroiler", "sort_order": 5},
    ],
    "SpeciesType": [
        {"code": "CHICKEN", "name": "Kuku", "sort_order": 1},
        {"code": "DUCK", "name": "Bata", "sort_order": 2},
        {"code": "RABBIT", "name": "Sungura", "sort_order": 3},
        {"code": "FISH", "name": "Samaki", "sort_order": 4},
    ],
    "FlockBatchStatus": [
        {"code": "ACTIVE", "name": "Active", "sort_order": 1},
        {"code": "DEPLETED", "name": "Depleted", "sort_order": 2},
        {"code": "QUARANTINED", "name": "Quarantined", "sort_order": 3},
        {"code": "PROCESSING", "name": "In Processing Plant", "sort_order": 4},
    ],
    "IncubatorMachineType": [
        {"code": "SETTER", "name": "Setter", "sort_order": 1},
        {"code": "HATCHER", "name": "Hatcher", "sort_order": 2},
        {"code": "COMBINED", "name": "Combined (Setter & Hatcher)", "sort_order": 3},
    ],
    "FarmBlockStatus": [
        {"code": "RESTING", "name": "Inapumzika", "sort_order": 1},
        {"code": "GRAZING", "name": "Kuku wapo hapa", "sort_order": 2},
        {"code": "CROPPING", "name": "Kuna Mazao", "sort_order": 3},
    ],
    "IncubationCycleStatus": [
        {"code": "SETTING", "name": "Setting", "sort_order": 1},
        {"code": "CANDLING", "name": "Candling", "sort_order": 2},
        {"code": "HATCHED", "name": "Hatched", "sort_order": 3},
        {"code": "FAILED", "name": "Failed", "sort_order": 4},
    ],
    "StockReadinessStatus": [
        {"code": "READY", "name": "Ready for Sale", "sort_order": 1},
        {"code": "NOT_READY", "name": "Not Ready / WIP", "sort_order": 2},
        {"code": "QUARANTINE", "name": "Under Inspection", "sort_order": 3},
        {"code": "EXPIRED", "name": "Expired / Waste", "sort_order": 4},
    ],
    "HealthRecordType": [
        {"code": "VACCINATION", "name": "Vaccination", "sort_order": 1},
        {"code": "MEDICATION", "name": "Medication/Treatment", "sort_order": 2},
        {"code": "PROCEDURE", "name": "General Procedure (e.g., De-beaking)", "sort_order": 3},
        {"code": "LAB_RESULT", "name": "Laboratory Test Result", "sort_order": 4},
    ],
    "DiseaseOutbreakStatus": [
        {"code": "ACTIVE", "name": "Active Outbreak", "sort_order": 1},
        {"code": "CONTAINED", "name": "Contained/Under Treatment", "sort_order": 2},
        {"code": "RESOLVED", "name": "Resolved/Closed", "sort_order": 3},
    ],
    "WasteDisposalMethod": [
        {"code": "INCINERATION", "name": "Incineration", "sort_order": 1},
        {"code": "COMPOSTING", "name": "Composting", "sort_order": 2},
        {"code": "SALE", "name": "Sale to Third Party", "sort_order": 3},
        {"code": "LANDFILL", "name": "Landfill", "sort_order": 4},
        {"code": "RECYCLE", "name": "Recycling", "sort_order": 5},
    ],
    "ProductionStatus": [
        {"code": "PLANTED", "name": "Planted", "sort_order": 1},
        {"code": "GROWING", "name": "Growing", "sort_order": 2},
        {"code": "HARVESTED", "name": "Harvested", "sort_order": 3},
        {"code": "FAILED", "name": "Failed", "sort_order": 4},
    ],
    "MeatCutType": [
        {"code": "SLICE", "name": "Slice / Steak (Lidandi / Shaba)", "sort_order": 1},
        {"code": "PART", "name": "Primal Part / Cut", "sort_order": 2},
        {"code": "PIECE", "name": "Countable Piece", "sort_order": 3},
        {"code": "WHOLE", "name": "Whole Carcass / Bird", "sort_order": 4},
    ],
    "StorageState": [
        {"code": "FRESH", "name": "Fresh / Chilled", "sort_order": 1},
        {"code": "FROZEN", "name": "Frozen", "sort_order": 2},
    ],
    "FatLevel": [
        {"code": "LEAN", "name": "Lean / Low Fat", "sort_order": 1},
        {"code": "MEDIUM", "name": "Medium Fat", "sort_order": 2},
        {"code": "HIGH", "name": "High Fat / Premium Marbled", "sort_order": 3},
    ],
    "CurrencyCode": [
        {"code": "TZS", "name": "Tanzanian Shilling", "sort_order": 1},
        {"code": "GBP", "name": "British Pound", "sort_order": 2},
        {"code": "USD", "name": "US Dollar", "sort_order": 3},
        {"code": "KES", "name": "Kenyan Shilling", "sort_order": 4},
    ],
    "PaymentMethod": [
        {"code": "CASH", "name": "Cash", "sort_order": 1},
        {"code": "CREDIT_CARD", "name": "Credit Card", "sort_order": 2},
        {"code": "BANK_TRANSFER", "name": "Bank Transfer", "sort_order": 3},
        {"code": "MOBILE_MONEY", "name": "Mobile Money (M-Pesa/Tigo/Airtel)", "sort_order": 4},
        {"code": "ONLINE_WALLET", "name": "Online Wallet", "sort_order": 5},
    ],
    "SaleInvoiceStatus": [
        {"code": "PENDING", "name": "Pending", "sort_order": 1},
        {"code": "PARTIAL", "name": "Partial", "sort_order": 2},
        {"code": "PAID", "name": "Paid", "sort_order": 3},
        {"code": "FAILED", "name": "Failed", "sort_order": 4},
        {"code": "REFUNDED", "name": "Refunded", "sort_order": 5},
    ],
    "CustomerType": [
        {"code": "RETAIL", "name": "Retail", "sort_order": 1},
        {"code": "WHOLESALE", "name": "Wholesale", "sort_order": 2},
        {"code": "DISTRIBUTOR", "name": "Distributor", "sort_order": 3},
    ],
    "EventBookingStatus": [
        {"code": "PENDING", "name": "Pending/Inquiry", "sort_order": 1},
        {"code": "CONFIRMED", "name": "Confirmed/Deposit Paid", "sort_order": 2},
        {"code": "CANCELLED", "name": "Cancelled", "sort_order": 3},
        {"code": "COMPLETED", "name": "Event Finished", "sort_order": 4},
    ],
    "AssetType": [
        {"code": "FARM", "name": "Farm/Production Site", "sort_order": 1},
        {"code": "BUILDING", "name": "Building/Structure", "sort_order": 2},
        {"code": "ZONE", "name": "Recreation/Common Zone", "sort_order": 3},
        {"code": "UNIT", "name": "Specific Rental/Housing Unit", "sort_order": 4},
    ],
    "RentalUnitType": [
        {"code": "SINGLE", "name": "Single Room", "sort_order": 1},
        {"code": "BEDSITTER", "name": "Bedsitter", "sort_order": 2},
        {"code": "APARTMENT", "name": "Full Apartment", "sort_order": 3},
        {"code": "SHOP", "name": "Commercial Shop Space", "sort_order": 4},
    ],
    "UnitOfMeasure": [
        {"code": "TRAY", "name": "Tray (Treya)", "sort_order": 1},
        {"code": "KG", "name": "Kilogram (Kilogramu)", "sort_order": 2},
        {"code": "LITER", "name": "Liter (Lita)", "sort_order": 3},
        {"code": "PCS", "name": "Pieces (Idadi/Vipande)", "sort_order": 4},
        {"code": "BAG", "name": "Bag (Mfuko)", "sort_order": 5},
        {"code": "BOX", "name": "Box (Boxi)", "sort_order": 6},
    ],
    "RateType": [
        {"code": "FLAT", "name": "Flat Rate", "sort_order": 1},
        {"code": "PER_KG", "name": "Cost Per KG", "sort_order": 2},
    ],
    "TicketStatus": [
        {"code": "OPEN", "name": "Open", "sort_order": 1},
        {"code": "IN_PROGRESS", "name": "In Progress", "sort_order": 2},
        {"code": "CLOSED", "name": "Resolved", "sort_order": 3},
    ],
    "TaskPriority": [
        {"code": "LOW", "name": "Low", "sort_order": 1},
        {"code": "NORMAL", "name": "Normal", "sort_order": 2},
        {"code": "URGENT", "name": "Urgent/Safety", "sort_order": 3},
    ]
}

# --- SPECIAL SEED LIST FOR DEPENDENT MULTI-RELATIONAL RECORD: BREED TYPES ---
BREED_SEED_DATA = [
    {"species_code": "CHICKEN", "code": "KUCHI", "name": "Kuchi"},
    {"species_code": "CHICKEN", "code": "SINGAMAGAZI", "name": "Singamagazi"},
    {"species_code": "CHICKEN", "code": "CHINGWEKWE", "name": "Chingwekwe"},
    {"species_code": "CHICKEN", "code": "KISHINGO", "name": "Kishingo"},
    {"species_code": "CHICKEN", "code": "MBEYA", "name": "Mbeya"},
    {"species_code": "CHICKEN", "code": "KIBUTU", "name": "Kibutu"},
    {"species_code": "DUCK", "code": "MZINGA", "name": "Bata Mzinga"},
    {"species_code": "DUCK", "code": "BUKINI", "name": "Bata Bukini"},
    {"species_code": "DUCK", "code": "MAJI", "name": "Bata Maji (Muscovy/Mallard)"},
    {"species_code": "RABBIT", "code": "NZ_WHITE", "name": "New Zealand White"},
    {"species_code": "RABBIT", "code": "CALIFORNIA", "name": "California White"},
    {"species_code": "RABBIT", "code": "CHINCHILLA", "name": "Chinchilla"},
    {"species_code": "RABBIT", "code": "FLEMISH", "name": "Flemish Giant"},
    {"species_code": "RABBIT", "code": "S_LOCAL", "name": "Sungura wa Kienyeji (Local)"},
    {"species_code": "FISH", "code": "PEREGE", "name": "Perege (Tilapia)"},
    {"species_code": "FISH", "code": "KAMBALE", "name": "Kambale (Catfish)"},
]
