# Generated by Django 6.0.2 on 2026-06-06 15:15

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hrms", "0002_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("postcode", models.CharField(db_index=True, max_length=5)),
                ("address_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Farm Name"
                    ),
                ),
                (
                    "site_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores utility types, acreage, and regional site settings.",
                        verbose_name="Site Configuration",
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all batch movements and processing sessions are blocked for bio-security.",
                        verbose_name="Quarantine Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_sites",
                        to="hrms.employee",
                        verbose_name="Farm Manager",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "db_table": "farm",
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["site_config"], name="farm_site_cfg_gin_idx"
                    )
                ],
            },
        ),
    ]
