# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0001_initial"),
        ("hrms", "0001_initial"),
        ("ppms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Batch ID",
                    ),
                ),
                (
                    "initial_count",
                    models.PositiveIntegerField(verbose_name="Initial Bird Count"),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(verbose_name="Current Bird Count"),
                ),
                (
                    "expected_depletion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Depletion"
                    ),
                ),
                (
                    "batch_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Batch Details"
                    ),
                ),
                (
                    "bird_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.birdtype",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.breedtype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.speciestype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.flockbatchstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch",
                "verbose_name_plural": "Flock Batches",
                "db_table": "batch",
            },
        ),
        migrations.CreateModel(
            name="BreederFlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "breed_line",
                    models.CharField(max_length=100, verbose_name="Breed Line"),
                ),
                (
                    "genetic_source",
                    models.CharField(max_length=255, verbose_name="Genetic Origin"),
                ),
                (
                    "traits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores phenotypic and performance targets for this breed line.",
                        verbose_name="Genetic Traits",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeder_details",
                        to="sfap.batch",
                        verbose_name="Source Batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Breeder Flock",
                "verbose_name_plural": "Breeder Flocks",
                "db_table": "breeder_flock",
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                (
                    "growth_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores conduncive conditions for succesfullly crop growth.",
                        verbose_name="Growth conditions for a crop",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop",
                "verbose_name_plural": "Crops",
                "db_table": "crop",
                "ordering": ["crop_name"],
            },
        ),
        migrations.CreateModel(
            name="DailyObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "mortality_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mortality"),
                ),
                ("culls", models.PositiveIntegerField(default=0, verbose_name="Culls")),
                (
                    "eggs_collected",
                    models.IntegerField(default=0, verbose_name="Eggs Collected"),
                ),
                (
                    "manure_volume_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "environmental_data",
                    models.JSONField(
                        default=dict, verbose_name="Environmental & Feeding Data"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sfap.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Observation",
                "verbose_name_plural": "Flock Observations",
                "db_table": "daily_observation",
            },
        ),
        migrations.CreateModel(
            name="DiseaseOutbreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "suspected_disease",
                    models.CharField(
                        max_length=255, verbose_name="Suspected Disease/Condition"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "diagnostic_data",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed symptoms, lab results, and containment measures.",
                        verbose_name="Diagnostic & Quarantine Data",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.batch",
                        verbose_name="Impacted Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.diseaseoutbreakstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Outbreak",
                "verbose_name_plural": "Disease Outbreaks",
                "db_table": "disease_outbreak",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("postcode", models.CharField(db_index=True, max_length=5)),
                ("address_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Farm Name"
                    ),
                ),
                (
                    "site_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores utility types, acreage, and regional site settings.",
                        verbose_name="Site Configuration",
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all batch movements and processing sessions are blocked for bio-security.",
                        verbose_name="Quarantine Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_sites",
                        to="hrms.employee",
                        verbose_name="Farm Manager",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "db_table": "farm",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FarmBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size_acres", models.DecimalField(decimal_places=2, max_digits=5)),
                ("soil_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="sfap.farm",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Inatusaidia kuratibu mzunguko wa ikolojia kati ya kuku na mazao.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.farmblockstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EcologicalInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("input_name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estimated_cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "estimated_cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, verbose_name="Gharama kwa TZS"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        help_text="Meli/Kitalu gani imetoka",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.farmblock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CropProduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("planting_date", models.DateField()),
                ("harvest_date", models.DateField(blank=True, null=True)),
                (
                    "manure_used_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("production_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_yield_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "actual_yield_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crops",
                    models.ManyToManyField(related_name="crops_grown", to="sfap.crop"),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.productionstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops_block",
                        to="sfap.farmblock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="current_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sfap.farmblock",
            ),
        ),
        migrations.CreateModel(
            name="FarmShed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Shed Name")),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Max Capacity (Birds)"),
                ),
                (
                    "shed_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Shed Specifications"
                    ),
                ),
                (
                    "last_empty_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the previous batch was cleared. Used to ensure a 14-day bio-security break.",
                        null=True,
                        verbose_name="Last Date Empty",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sheds",
                        to="sfap.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Shed",
                "db_table": "shed",
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="sfap.farmshed",
            ),
        ),
        migrations.CreateModel(
            name="FarmVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Plate Number"
                    ),
                ),
                (
                    "max_payload_kg",
                    models.PositiveIntegerField(verbose_name="Max Payload (KG)"),
                ),
                (
                    "vehicle_specs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vehicle Specifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.farmvehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Vehicle",
                "verbose_name_plural": "Farm Vehicles",
                "db_table": "farm_vehicle",
            },
        ),
        migrations.CreateModel(
            name="FeedIngredientStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=100)),
                (
                    "available_qty_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "unit_cost_per_kg_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_cost_per_kg",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, verbose_name="Gharama kwa TZS"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_stock",
                        to="sfap.farm",
                        verbose_name="Farm Ingredient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Protocol Name"),
                ),
                (
                    "protocol_steps",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of scheduled health tasks by bird age (days).",
                        verbose_name="Protocol Steps",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Detailed Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_bird_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.birdtype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Protocol",
                "verbose_name_plural": "Health Protocols",
                "db_table": "health_protocol",
            },
        ),
        migrations.CreateModel(
            name="IncubationCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "cycle_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Cycle Number",
                    ),
                ),
                (
                    "eggs_set_count",
                    models.PositiveIntegerField(verbose_name="Total Eggs Set"),
                ),
                (
                    "expected_hatch_date",
                    models.DateTimeField(verbose_name="Expected Hatch Date"),
                ),
                (
                    "incubation_logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic logs for candling results, machine temps, and embryo health.",
                        verbose_name="Incubation & Candling Logs",
                    ),
                ),
                ("actual_hatch_date", models.DateTimeField(blank=True, null=True)),
                (
                    "breeder_flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incubation_cycles",
                        to="sfap.breederflock",
                        verbose_name="Breeder Flock",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.incubationcyclestatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubation Cycle",
                "db_table": "incubation_cycle",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="HatchRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("is_added_to_inventory", models.BooleanField(default=False)),
                (
                    "total_chicks_hatched",
                    models.PositiveIntegerField(verbose_name="Total Chicks Hatched"),
                ),
                (
                    "grade_a_chicks",
                    models.PositiveIntegerField(verbose_name="Grade A Chicks"),
                ),
                (
                    "grade_b_chicks",
                    models.PositiveIntegerField(verbose_name="Grade B Chicks"),
                ),
                (
                    "grade_c_chicks",
                    models.PositiveIntegerField(verbose_name="Grade C Chicks"),
                ),
                (
                    "quality_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed health data, weights, and vaccination records.",
                        verbose_name="Quality Metrics",
                    ),
                ),
                (
                    "hatchability_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Hatchability (%)",
                    ),
                ),
                (
                    "cull_weight_total",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Tracks the weight of rejected chicks for waste management.",
                        max_digits=10,
                        verbose_name="Total Cull Weight (KG)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The production batch these chicks were moved to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfap.batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incubation_cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatch_record",
                        to="sfap.incubationcycle",
                        verbose_name="Incubation Cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatch Record",
                "verbose_name_plural": "Hatch Records",
                "db_table": "hatch_record",
            },
        ),
        migrations.CreateModel(
            name="Incubator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Machine Code or Machine Identification (Short code like 'INC-01')",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Incubator features"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Total number of eggs this machine can hold.",
                        verbose_name="Max Egg Capacity",
                    ),
                ),
                (
                    "last_sanitized",
                    models.DateTimeField(
                        blank=True,
                        help_text="Tracks bio-security/cleaning dates between cycles.",
                        null=True,
                        verbose_name="Last Sanitization Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incubators",
                        to="sfap.farm",
                        verbose_name="Location/Farm",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.incubatormachinetype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubator",
                "verbose_name_plural": "Incubators",
                "db_table": "incubator",
            },
        ),
        migrations.AddField(
            model_name="incubationcycle",
            name="hatcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hatching_cycles",
                to="sfap.incubator",
                verbose_name="Incubator Machine",
            ),
        ),
        migrations.CreateModel(
            name="ManagerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "tenure_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tenure Metadata"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Current Manager"),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="management_history",
                        to="sfap.farm",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_tenures",
                        to="hrms.employee",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Plant_management_history",
                        to="ppms.processingplant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager History",
                "db_table": "audit_manager_lifecycle",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "date_of_administration",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date of Administration",
                    ),
                ),
                (
                    "event_details",
                    models.JSONField(
                        default=dict,
                        help_text="Stores item names, batch numbers, and administration methods.",
                        verbose_name="Event Details",
                    ),
                ),
                (
                    "cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=djmoney.money.Money(0.0, "TZS"),
                        max_digits=14,
                        verbose_name="Total Cost",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Clinical Notes")),
                ("withdrawal_end_date", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="sfap.batch",
                        verbose_name="Flock Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="config.healthrecordtype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_record",
                "ordering": ["-date_of_administration"],
            },
        ),
        migrations.CreateModel(
            name="TransportMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "transit_data",
                    models.JSONField(default=dict, verbose_name="Transit Audit Data"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hrms.employee"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.farmvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport Movement",
                "verbose_name_plural": "Transport Movements",
                "db_table": "transport_movement",
            },
        ),
        migrations.AddIndex(
            model_name="breederflock",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["traits"], name="breeder_traits_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["growth_conditions"], name="growth_conditions_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyobservation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["environmental_data"], name="daily_env_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyobservation",
            unique_together={("batch", "created_on")},
        ),
        migrations.AddIndex(
            model_name="diseaseoutbreak",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["diagnostic_data"], name="outbreak_diag_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["site_config"], name="farm_site_cfg_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmshed",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["shed_metadata"], name="shed_spec_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmshed",
            unique_together={("farm", "name")},
        ),
        migrations.AddIndex(
            model_name="batch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["batch_details"], name="batch_details_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmvehicle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vehicle_specs"], name="vehicle_specs_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthprotocol",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["protocol_steps"], name="health_protocol_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hatchrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["quality_metrics"], name="hatch_quality_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incubator",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["features"], name="incubator_features_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incubationcycle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["incubation_logs"], name="incubation_log_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="managerhistory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tenure_metadata"], name="mgr_history_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["event_details"], name="medical_event_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportmovement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["transit_data"], name="transit_data_gin_idx"
            ),
        ),
    ]
