# Generated by Django 6.0.2 on 2026-06-06 15:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_employee"),
        ("ppms", "0001_initial"),
        ("sfap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "tenure_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tenure Metadata"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Current Manager"),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="management_history",
                        to="sfap.farm",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_tenures",
                        to="hrms.employee",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Plant_management_history",
                        to="ppms.processingplant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager History",
                "db_table": "audit_manager_lifecycle",
                "ordering": ["-start_date"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["tenure_metadata"], name="mgr_history_gin_idx"
                    )
                ],
            },
        ),
    ]
