# Generated by Django 6.0.2 on 2026-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="breederflock",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="cropproduction",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="dailyobservation",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="diseaseoutbreak",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="ecologicalinput",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="farmblock",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="farmshed",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="farmvehicle",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="feedingredientstock",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="hatchrecord",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="healthprotocol",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="incubationcycle",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="incubator",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="transportmovement",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
    ]
