# Generated by Django 6.0.2 on 2026-06-13 19:26

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_useraddress"),
        ("sfap", "0002_managerhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size_acres", models.DecimalField(decimal_places=2, max_digits=5)),
                ("soil_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="sfap.farm",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Inatusaidia kuratibu mzunguko wa ikolojia kati ya kuku na mazao.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.farmblockstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FarmShed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Shed Name")),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Max Capacity (Birds)"),
                ),
                (
                    "shed_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Shed Specifications"
                    ),
                ),
                (
                    "last_empty_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the previous batch was cleared. Used to ensure a 14-day bio-security break.",
                        null=True,
                        verbose_name="Last Date Empty",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sheds",
                        to="sfap.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Shed",
                "db_table": "shed",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Batch ID",
                    ),
                ),
                (
                    "initial_count",
                    models.PositiveIntegerField(verbose_name="Initial Bird Count"),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(verbose_name="Current Bird Count"),
                ),
                (
                    "expected_depletion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Depletion"
                    ),
                ),
                (
                    "batch_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Batch Details"
                    ),
                ),
                (
                    "bird_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.birdtype"
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.breedtype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.speciestype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.flockbatchstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfap.farmblock",
                    ),
                ),
                (
                    "shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sfap.farmshed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch",
                "verbose_name_plural": "Flock Batches",
                "db_table": "batch",
            },
        ),
        migrations.CreateModel(
            name="BreederFlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "breed_line",
                    models.CharField(max_length=100, verbose_name="Breed Line"),
                ),
                (
                    "genetic_source",
                    models.CharField(max_length=255, verbose_name="Genetic Origin"),
                ),
                (
                    "traits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores phenotypic and performance targets for this breed line.",
                        verbose_name="Genetic Traits",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeder_details",
                        to="sfap.batch",
                        verbose_name="Source Batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Breeder Flock",
                "verbose_name_plural": "Breeder Flocks",
                "db_table": "breeder_flock",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["traits"], name="breeder_traits_gin_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "mortality_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mortality"),
                ),
                ("culls", models.PositiveIntegerField(default=0, verbose_name="Culls")),
                (
                    "eggs_collected",
                    models.IntegerField(default=0, verbose_name="Eggs Collected"),
                ),
                (
                    "manure_volume_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "environmental_data",
                    models.JSONField(
                        default=dict, verbose_name="Environmental & Feeding Data"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sfap.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Observation",
                "verbose_name_plural": "Flock Observations",
                "db_table": "daily_observation",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["environmental_data"], name="daily_env_gin_idx"
                    )
                ],
                "unique_together": {("batch", "created_on")},
            },
        ),
        migrations.AddIndex(
            model_name="farmshed",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["shed_metadata"], name="shed_spec_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmshed",
            unique_together={("farm", "name")},
        ),
        migrations.AddIndex(
            model_name="batch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["batch_details"], name="batch_details_gin_idx"
            ),
        ),
    ]
