# Generated by Django 6.0.2 on 2026-05-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppms", "0001_initial"),
        ("sfap", "0002_managerhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerhistory",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Plant_management_history",
                to="ppms.processingplant",
            ),
        ),
    ]
