# Generated by Django 6.0.2 on 2026-05-17 07:29

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0003_managerhistory_plant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmShed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Shed Name")),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Max Capacity (Birds)"),
                ),
                (
                    "shed_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Shed Specifications"
                    ),
                ),
                (
                    "last_empty_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the previous batch was cleared. Used to ensure a 14-day bio-security break.",
                        null=True,
                        verbose_name="Last Date Empty",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sheds",
                        to="sfap.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Shed",
                "db_table": "shed",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Batch ID",
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("BROILER", "Broiler"),
                            ("LAYER", "Layer"),
                            ("KUCHI", "Kuchi"),
                            ("LOCAL", "Local"),
                        ],
                        max_length=20,
                        verbose_name="Bird Type",
                    ),
                ),
                (
                    "initial_count",
                    models.PositiveIntegerField(verbose_name="Initial Bird Count"),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(verbose_name="Current Bird Count"),
                ),
                (
                    "expected_depletion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Depletion"
                    ),
                ),
                (
                    "batch_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Batch Details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEPLETED", "Depleted"),
                            ("QUARANTINED", "Quarantined"),
                            ("PROCESSING", "In Processing Plant"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sfap.farmshed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch",
                "verbose_name_plural": "Flock Batches",
                "db_table": "batch",
            },
        ),
        migrations.AddIndex(
            model_name="farmshed",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["shed_metadata"], name="shed_spec_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmshed",
            unique_together={("farm", "name")},
        ),
        migrations.AddIndex(
            model_name="batch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["batch_details"], name="batch_details_gin_idx"
            ),
        ),
    ]
