# Generated by Django 6.0.2 on 2026-05-17 09:59

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0004_farmshed_batch_farmshed_shed_spec_gin_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="bird_type",
            field=models.CharField(
                choices=[
                    ("BROILER", "Broiler"),
                    ("LAYER", "Layer"),
                    ("KUCHI", "Kuchi"),
                    ("LOCAL", "Local"),
                    ("KUROILER", "Kuroiler"),
                ],
                max_length=20,
                verbose_name="Bird Type",
            ),
        ),
        migrations.CreateModel(
            name="DailyObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "mortality_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mortality"),
                ),
                ("culls", models.PositiveIntegerField(default=0, verbose_name="Culls")),
                (
                    "environmental_data",
                    models.JSONField(
                        default=dict, verbose_name="Environmental & Feeding Data"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sfap.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Observation",
                "verbose_name_plural": "Flock Observations",
                "db_table": "daily_observation",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["environmental_data"], name="daily_env_gin_idx"
                    )
                ],
                "unique_together": {("batch", "created_on")},
            },
        ),
    ]
