# Generated by Django 6.0.2 on 2026-06-06 15:27

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0004_farmblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Batch ID",
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("BROILER", "Broiler"),
                            ("LAYER", "Layer"),
                            ("KUCHI", "Kuchi"),
                            ("LOCAL", "Local"),
                            ("KUROILER", "Kuroiler"),
                        ],
                        max_length=20,
                        verbose_name="Bird Type",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("CHICKEN", "Kuku"),
                            ("DUCK", "Bata"),
                            ("RABBIT", "Sungura"),
                            ("FISH", "Samaki"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        choices=[
                            ("KUCHI", "Kuchi"),
                            ("SINGAMAGAZI", "Singamagazi"),
                            ("CHINGWEKWE", "Chingwekwe"),
                            ("KISHINGO", "Kishingo"),
                            ("MBEYA", "Mbeya"),
                            ("KIBUTU", "Kibutu"),
                            ("MZINGA", "Bata Mzinga"),
                            ("BUKINI", "Bata Bukini"),
                            ("MAJI", "Bata Maji (Muscovy/Mallard)"),
                            ("NZ_WHITE", "New Zealand White"),
                            ("CALIFORNIA", "California White"),
                            ("CHINCHILLA", "Chinchilla"),
                            ("FLEMISH", "Flemish Giant"),
                            ("S_LOCAL", "Sungura wa Kienyeji (Local)"),
                            ("PEREGE", "Perege (Tilapia)"),
                            ("KAMBALE", "Kambale (Catfish)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "initial_count",
                    models.PositiveIntegerField(verbose_name="Initial Bird Count"),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(verbose_name="Current Bird Count"),
                ),
                (
                    "expected_depletion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Depletion"
                    ),
                ),
                (
                    "batch_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Batch Details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEPLETED", "Depleted"),
                            ("QUARANTINED", "Quarantined"),
                            ("PROCESSING", "In Processing Plant"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfap.farmblock",
                    ),
                ),
                (
                    "shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sfap.farmshed",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch",
                "verbose_name_plural": "Flock Batches",
                "db_table": "batch",
            },
        ),
        migrations.CreateModel(
            name="BreederFlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "breed_line",
                    models.CharField(max_length=100, verbose_name="Breed Line"),
                ),
                (
                    "genetic_source",
                    models.CharField(max_length=255, verbose_name="Genetic Origin"),
                ),
                (
                    "traits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores phenotypic and performance targets for this breed line.",
                        verbose_name="Genetic Traits",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeder_details",
                        to="sfap.batch",
                        verbose_name="Source Batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Breeder Flock",
                "verbose_name_plural": "Breeder Flocks",
                "db_table": "breeder_flock",
            },
        ),
        migrations.CreateModel(
            name="DailyObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "mortality_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mortality"),
                ),
                ("culls", models.PositiveIntegerField(default=0, verbose_name="Culls")),
                (
                    "eggs_collected",
                    models.IntegerField(default=0, verbose_name="Eggs Collected"),
                ),
                (
                    "manure_volume_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "environmental_data",
                    models.JSONField(
                        default=dict, verbose_name="Environmental & Feeding Data"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sfap.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Observation",
                "verbose_name_plural": "Flock Observations",
                "db_table": "daily_observation",
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["batch_details"], name="batch_details_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breederflock",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["traits"], name="breeder_traits_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyobservation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["environmental_data"], name="daily_env_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyobservation",
            unique_together={("batch", "created_on")},
        ),
    ]
