# Generated by Django 6.0.2 on 2026-05-17 10:16

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0005_alter_batch_bird_type_dailyobservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreederFlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "breed_line",
                    models.CharField(max_length=100, verbose_name="Breed Line"),
                ),
                (
                    "genetic_source",
                    models.CharField(max_length=255, verbose_name="Genetic Origin"),
                ),
                (
                    "traits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores phenotypic and performance targets for this breed line.",
                        verbose_name="Genetic Traits",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeder_details",
                        to="sfap.batch",
                        verbose_name="Source Batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Breeder Flock",
                "verbose_name_plural": "Breeder Flocks",
                "db_table": "breeder_flock",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["traits"], name="breeder_traits_gin_idx"
                    )
                ],
            },
        ),
    ]
