# Generated by Django 6.0.2 on 2026-06-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_useraddress"),
        ("sfap", "0005_alter_batch_created_by_alter_batch_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cropproduction",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.productionstatus"
            ),
        ),
    ]
