# Generated by Django 6.0.2 on 2026-06-06 16:06

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0003_employee_assigned_block_employee_assigned_plant_and_more"),
        ("sfap", "0005_batch_breederflock_dailyobservation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Plate Number"
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "max_payload_kg",
                    models.PositiveIntegerField(verbose_name="Max Payload (KG)"),
                ),
                (
                    "vehicle_specs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vehicle Specifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Vehicle",
                "verbose_name_plural": "Farm Vehicles",
                "db_table": "farm_vehicle",
            },
        ),
        migrations.CreateModel(
            name="HealthProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Protocol Name"),
                ),
                (
                    "target_bird_type",
                    models.CharField(
                        choices=[
                            ("BROILER", "Broiler"),
                            ("LAYER", "Layer"),
                            ("KUCHI", "Kuchi"),
                            ("LOCAL", "Local"),
                            ("KUROILER", "Kuroiler"),
                        ],
                        max_length=50,
                        verbose_name="Target Bird Type",
                    ),
                ),
                (
                    "protocol_steps",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of scheduled health tasks by bird age (days).",
                        verbose_name="Protocol Steps",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Detailed Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Protocol",
                "verbose_name_plural": "Health Protocols",
                "db_table": "health_protocol",
            },
        ),
        migrations.CreateModel(
            name="IncubationCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "cycle_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Cycle Number",
                    ),
                ),
                (
                    "eggs_set_count",
                    models.PositiveIntegerField(verbose_name="Total Eggs Set"),
                ),
                (
                    "expected_hatch_date",
                    models.DateTimeField(verbose_name="Expected Hatch Date"),
                ),
                (
                    "incubation_logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic logs for candling results, machine temps, and embryo health.",
                        verbose_name="Incubation & Candling Logs",
                    ),
                ),
                ("actual_hatch_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SETTING", "Setting"),
                            ("CANDLING", "Candling"),
                            ("HATCHED", "Hatched"),
                            ("FAILED", "Failed"),
                        ],
                        default="SETTING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "breeder_flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incubation_cycles",
                        to="sfap.breederflock",
                        verbose_name="Breeder Flock",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubation Cycle",
                "db_table": "incubation_cycle",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="HatchRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("is_added_to_inventory", models.BooleanField(default=False)),
                (
                    "total_chicks_hatched",
                    models.PositiveIntegerField(verbose_name="Total Chicks Hatched"),
                ),
                (
                    "grade_a_chicks",
                    models.PositiveIntegerField(verbose_name="Grade A Chicks"),
                ),
                (
                    "grade_b_chicks",
                    models.PositiveIntegerField(verbose_name="Grade B Chicks"),
                ),
                (
                    "grade_c_chicks",
                    models.PositiveIntegerField(verbose_name="Grade C Chicks"),
                ),
                (
                    "quality_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed health data, weights, and vaccination records.",
                        verbose_name="Quality Metrics",
                    ),
                ),
                (
                    "hatchability_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Hatchability (%)",
                    ),
                ),
                (
                    "cull_weight_total",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Tracks the weight of rejected chicks for waste management.",
                        max_digits=10,
                        verbose_name="Total Cull Weight (KG)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The production batch these chicks were moved to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfap.batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incubation_cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatch_record",
                        to="sfap.incubationcycle",
                        verbose_name="Incubation Cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatch Record",
                "verbose_name_plural": "Hatch Records",
                "db_table": "hatch_record",
            },
        ),
        migrations.CreateModel(
            name="Incubator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("SETTER", "Setter"),
                            ("HATCHER", "Hatcher"),
                            ("COMBINED", "Combined (Setter & Hatcher)"),
                        ],
                        default="COMBINED",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Machine Code or Machine Identification (Short code like 'INC-01')",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Incubator features"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Total number of eggs this machine can hold.",
                        verbose_name="Max Egg Capacity",
                    ),
                ),
                (
                    "last_sanitized",
                    models.DateTimeField(
                        blank=True,
                        help_text="Tracks bio-security/cleaning dates between cycles.",
                        null=True,
                        verbose_name="Last Sanitization Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incubators",
                        to="sfap.farm",
                        verbose_name="Location/Farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubator",
                "verbose_name_plural": "Incubators",
                "db_table": "incubator",
            },
        ),
        migrations.AddField(
            model_name="incubationcycle",
            name="hatcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hatching_cycles",
                to="sfap.incubator",
                verbose_name="Incubator Machine",
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "date_of_administration",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date of Administration",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("VACCINATION", "Vaccination"),
                            ("MEDICATION", "Medication/Treatment"),
                            ("PROCEDURE", "General Procedure (e.g., De-beaking)"),
                            ("LAB_RESULT", "Laboratory Test Result"),
                        ],
                        max_length=20,
                        verbose_name="Record Type",
                    ),
                ),
                (
                    "event_details",
                    models.JSONField(
                        default=dict,
                        help_text="Stores item names, batch numbers, and administration methods.",
                        verbose_name="Event Details",
                    ),
                ),
                (
                    "cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=djmoney.money.Money(0.0, "TZS"),
                        max_digits=14,
                        verbose_name="Total Cost",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Clinical Notes")),
                ("withdrawal_end_date", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="sfap.batch",
                        verbose_name="Flock Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_record",
                "ordering": ["-date_of_administration"],
            },
        ),
        migrations.CreateModel(
            name="TransportMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "transit_data",
                    models.JSONField(default=dict, verbose_name="Transit Audit Data"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hrms.employee"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.farmvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport Movement",
                "verbose_name_plural": "Transport Movements",
                "db_table": "transport_movement",
            },
        ),
        migrations.CreateModel(
            name="DiseaseOutbreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "suspected_disease",
                    models.CharField(
                        max_length=255, verbose_name="Suspected Disease/Condition"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "diagnostic_data",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed symptoms, lab results, and containment measures.",
                        verbose_name="Diagnostic & Quarantine Data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Outbreak"),
                            ("CONTAINED", "Contained/Under Treatment"),
                            ("RESOLVED", "Resolved/Closed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Incident Status",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.batch",
                        verbose_name="Impacted Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Outbreak",
                "verbose_name_plural": "Disease Outbreaks",
                "db_table": "disease_outbreak",
                "ordering": ["-created_on"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["diagnostic_data"], name="outbreak_diag_gin_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="farmvehicle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vehicle_specs"], name="vehicle_specs_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthprotocol",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["protocol_steps"], name="health_protocol_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hatchrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["quality_metrics"], name="hatch_quality_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incubator",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["features"], name="incubator_features_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incubationcycle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["incubation_logs"], name="incubation_log_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["event_details"], name="medical_event_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportmovement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["transit_data"], name="transit_data_gin_idx"
            ),
        ),
    ]
