# Generated by Django 6.0.2 on 2026-05-17 11:15

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0006_breederflock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incubator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("SETTER", "Setter"),
                            ("HATCHER", "Hatcher"),
                            ("COMBINED", "Combined (Setter & Hatcher)"),
                        ],
                        default="COMBINED",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Machine Code or Machine Identification (Short code like 'INC-01')",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Incubator features"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Total number of eggs this machine can hold.",
                        verbose_name="Max Egg Capacity",
                    ),
                ),
                (
                    "last_sanitized",
                    models.DateTimeField(
                        blank=True,
                        help_text="Tracks bio-security/cleaning dates between cycles.",
                        null=True,
                        verbose_name="Last Sanitization Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incubators",
                        to="sfap.farm",
                        verbose_name="Location/Farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubator",
                "verbose_name_plural": "Incubators",
                "db_table": "incubator",
            },
        ),
        migrations.CreateModel(
            name="IncubationCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "cycle_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Cycle Number",
                    ),
                ),
                (
                    "eggs_set_count",
                    models.PositiveIntegerField(verbose_name="Total Eggs Set"),
                ),
                (
                    "expected_hatch_date",
                    models.DateTimeField(verbose_name="Expected Hatch Date"),
                ),
                (
                    "incubation_logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic logs for candling results, machine temps, and embryo health.",
                        verbose_name="Incubation & Candling Logs",
                    ),
                ),
                ("actual_hatch_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SETTING", "Setting"),
                            ("CANDLING", "Candling"),
                            ("HATCHED", "Hatched"),
                            ("FAILED", "Failed"),
                        ],
                        default="SETTING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "breeder_flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incubation_cycles",
                        to="sfap.breederflock",
                        verbose_name="Breeder Flock",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hatcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hatching_cycles",
                        to="sfap.incubator",
                        verbose_name="Incubator Machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubation Cycle",
                "db_table": "incubation_cycle",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddIndex(
            model_name="incubator",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["features"], name="incubator_features_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incubationcycle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["incubation_logs"], name="incubation_log_gin_idx"
            ),
        ),
    ]
