# Generated by Django 6.0.2 on 2026-06-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_useraddress"),
        ("sfap", "0006_alter_cropproduction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecologicalinput",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.unitofmeasure"
            ),
        ),
    ]
