# Generated by Django 6.0.2 on 2026-06-17 19:40

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_farmvehicletype"),
        ("hrms", "0004_alter_department_created_by_and_more"),
        ("sfap", "0007_alter_ecologicalinput_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Plate Number"
                    ),
                ),
                (
                    "max_payload_kg",
                    models.PositiveIntegerField(verbose_name="Max Payload (KG)"),
                ),
                (
                    "vehicle_specs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vehicle Specifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.farmvehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Vehicle",
                "verbose_name_plural": "Farm Vehicles",
                "db_table": "farm_vehicle",
            },
        ),
        migrations.CreateModel(
            name="TransportMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "transit_data",
                    models.JSONField(default=dict, verbose_name="Transit Audit Data"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hrms.employee"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.farmvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport Movement",
                "verbose_name_plural": "Transport Movements",
                "db_table": "transport_movement",
            },
        ),
        migrations.AddIndex(
            model_name="farmvehicle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vehicle_specs"], name="vehicle_specs_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportmovement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["transit_data"], name="transit_data_gin_idx"
            ),
        ),
    ]
