# Generated by Django 6.0.2 on 2026-05-18 19:13

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0007_incubator_incubationcycle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HatchRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("is_added_to_inventory", models.BooleanField(default=False)),
                (
                    "total_chicks_hatched",
                    models.PositiveIntegerField(verbose_name="Total Chicks Hatched"),
                ),
                (
                    "grade_a_chicks",
                    models.PositiveIntegerField(verbose_name="Grade A Chicks"),
                ),
                (
                    "grade_b_chicks",
                    models.PositiveIntegerField(verbose_name="Grade B Chicks"),
                ),
                (
                    "grade_c_chicks",
                    models.PositiveIntegerField(verbose_name="Grade C Chicks"),
                ),
                (
                    "quality_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed health data, weights, and vaccination records.",
                        verbose_name="Quality Metrics",
                    ),
                ),
                (
                    "hatchability_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Hatchability (%)",
                    ),
                ),
                (
                    "cull_weight_total",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Tracks the weight of rejected chicks for waste management.",
                        max_digits=10,
                        verbose_name="Total Cull Weight (KG)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The production batch these chicks were moved to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfap.batch",
                    ),
                ),
                (
                    "incubation_cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatch_record",
                        to="sfap.incubationcycle",
                        verbose_name="Incubation Cycle",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatch Record",
                "db_table": "hatch_record",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["quality_metrics"], name="hatch_quality_gin_idx"
                    )
                ],
            },
        ),
    ]
