# Generated by Django 6.0.2 on 2026-05-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0008_hatchrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hatchrecord",
            options={
                "verbose_name": "Hatch Record",
                "verbose_name_plural": "Hatch Records",
            },
        ),
    ]
