# Generated by Django 6.0.2 on 2026-05-18 19:37

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0010_healthprotocol_medicalrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseOutbreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "suspected_disease",
                    models.CharField(
                        max_length=255, verbose_name="Suspected Disease/Condition"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "diagnostic_data",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed symptoms, lab results, and containment measures.",
                        verbose_name="Diagnostic & Quarantine Data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Outbreak"),
                            ("CONTAINED", "Contained/Under Treatment"),
                            ("RESOLVED", "Resolved/Closed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Incident Status",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.batch",
                        verbose_name="Impacted Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Outbreak",
                "verbose_name_plural": "Disease Outbreaks",
                "db_table": "disease_outbreak",
                "ordering": ["-created_on"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["diagnostic_data"], name="outbreak_diag_gin_idx"
                    )
                ],
            },
        ),
    ]
