# Generated by Django 6.0.2 on 2026-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0012_farmblock_batch_current_block_farmvehicle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyobservation",
            name="eggs_collected",
            field=models.IntegerField(default=0, verbose_name="Eggs Collected"),
        ),
        migrations.AddField(
            model_name="dailyobservation",
            name="manure_volume_kg",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
