# Generated by Django 6.0.2 on 2026-05-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0013_dailyobservation_eggs_collected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmblock",
            name="status",
            field=models.CharField(
                choices=[
                    ("RESTING", "Inapumzika"),
                    ("GRAZING", "Kuku wapo hapa"),
                    ("CROPPING", "Kuna Mazao"),
                ],
                default="RESTING",
                help_text="Inatusaidia kuratibu mzunguko wa ikolojia kati ya kuku na mazao.",
                max_length=20,
                verbose_name="Hali ya Kitalu",
            ),
        ),
    ]
