# Generated by Django 6.0.2 on 2026-03-22 12:19

import django.contrib.postgres.indexes
import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Employee Number",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time Regular"),
                            ("CONTRACT", "Contractor"),
                            ("CASUAL", "Casual Laborer"),
                        ],
                        default="FULL_TIME",
                        help_text="Determines benefits eligibility; e.g., Casuals usually don't get housing.",
                        max_length=20,
                        verbose_name="Employment Type",
                    ),
                ),
                (
                    "health_clearance_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Required for Processing Plant staff. Must be renewed annually.",
                        null=True,
                        verbose_name="Health Clearance Expiry",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Hire Date")),
                (
                    "base_salary_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "base_salary",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, verbose_name="Base Salary"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this instead of deleting the employee for audit history.",
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "hr_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores emergency contacts, ID numbers, skills, and payroll configurations.",
                        verbose_name="HR Metadata",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hrms.employee",
                        verbose_name="Reports To",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employee",
                "ordering": ["employee_number"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["hr_metadata"], name="emp_hr_meta_gin_idx"
                    )
                ],
            },
        ),
    ]
