# Generated by Django 6.0.2 on 2026-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_employee_assigned_plant_employee_assigned_shed"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_title",
            field=models.CharField(
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Employee Title",
            ),
        ),
    ]
