# Generated by Django 6.0.2 on 2026-03-23 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0003_employee_employee_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Department name"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Department Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "sub_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hrms.department",
                        verbose_name="Minor department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="hrms.department",
                verbose_name="Employee Department",
            ),
        ),
    ]
