# Generated by Django 6.0.2 on 2026-03-29 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0004_department_employee_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="department",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="department",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
