# Generated by Django 6.0.2 on 2026-03-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0005_remove_department_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="sub_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="hrms.department",
                verbose_name="Minor department",
            ),
        ),
    ]
