# Generated by Django 6.0.2 on 2026-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0006_alter_department_sub_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("maried", "Maried"),
                    ("devoced", "Devoced"),
                ],
                db_index=True,
                default="single",
                max_length=20,
                verbose_name="Marital Status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_title",
            field=models.CharField(
                choices=[
                    ("mr", "Mr"),
                    ("ms", "Ms"),
                    ("mrs", "Mrs"),
                    ("dr", "Doctor"),
                    ("prof", "Professor"),
                    ("eng", "Engineer"),
                ],
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Employee Title",
            ),
        ),
    ]
