# Generated by Django 6.0.2 on 2026-03-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0007_employee_marital_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Department name"
            ),
        ),
    ]
