# Generated by Django 6.0.2 on 2026-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0008_alter_department_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
