# Generated by Django 6.0.2 on 2026-03-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0009_department_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelTable(
            name="department",
            table="department",
        ),
    ]
