# Generated by Django 6.0.2 on 2026-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0010_alter_department_options_alter_department_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["created_by"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
    ]
