# Generated by Django 6.0.2 on 2026-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0011_alter_department_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["employee_number"],
                "permissions": [
                    ("can_deactivate_employee", "Can deactivate employee"),
                    (
                        "can_change_employee_department",
                        "Can change employee department",
                    ),
                    ("can_change_employee_type", "Can change employee type"),
                    ("can_assign_shed", "Can assign shed"),
                    ("can_change_shed", "Can change shed"),
                    ("can_assign_plant", "Can assign plant"),
                    ("can_change_plant", "Can change plant"),
                    ("can_add_health_clearance", "Can add health clearance"),
                    ("can_add_salary", "Can add salary"),
                    ("can_change_salary", "Can change salary"),
                ],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("mr", "Mr"),
                    ("ms", "Ms"),
                    ("mrs", "Mrs"),
                    ("dr", "Doctor"),
                    ("prof", "Professor"),
                    ("eng", "Engineer"),
                ],
                max_length=20,
                null=True,
                verbose_name="Employee Gender",
            ),
        ),
    ]
