# Generated by Django 6.0.2 on 2026-04-11 15:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0012_alter_employee_options_employee_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=100, verbose_name="middle name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Enter phone number in international format (e.g. +255...)",
                        max_length=128,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "physical_address",
                    models.CharField(max_length=200, verbose_name="physical address"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this next of kin belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kin_contacts",
                        to="hrms.employee",
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Next of Kin",
                "verbose_name_plural": "Next of Kin",
                "db_table": "next_of_kin",
                "ordering": ["first_name", "middle_name", "last_name"],
            },
        ),
    ]
