# Generated by Django 6.0.2 on 2026-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0013_nextofkin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer Not to Say"),
                ],
                max_length=20,
                null=True,
                verbose_name="Employee Gender",
            ),
        ),
    ]
