# Generated by Django 6.0.2 on 2026-04-11 19:37

import django.core.validators
import django.db.models.deletion
import helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0014_alter_employee_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[
                            ("NIDA", "NIDA (National ID)"),
                            ("PASSPORT", "Passport"),
                            ("VOTER_ID", "Voter ID"),
                            ("DRIVING_LICENSE", "Driving License"),
                        ],
                        max_length=20,
                        verbose_name="Identity Type",
                    ),
                ),
                (
                    "identity_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Identity Number"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "id_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.validators.upload_personal_id,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            ),
                            helpers.validators.MimeTypeValidator(
                                [
                                    "image/jpg",
                                    "image/jpeg",
                                    "image/png",
                                    "application/pdf",
                                ]
                            ),
                        ],
                        verbose_name="ID Scan/Photo",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="hrms.employee",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Identity",
                "verbose_name_plural": "Employee Identities",
                "db_table": "employee_identity",
                "unique_together": {("owner", "identity_type")},
            },
        ),
    ]
