# Generated by Django 6.0.2 on 2026-04-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0015_useridentity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nextofkin",
            old_name="user",
            new_name="owner",
        ),
    ]
