# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address/Location Type",
                "verbose_name_plural": "Address/Location Types",
                "db_table": "address_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Structural Corporate Asset Type",
                "verbose_name_plural": "Fixed Structural Corporate Asset Types",
                "db_table": "asset_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BirdType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avian Bird Classification Type",
                "verbose_name_plural": "Avian Bird Classification Types",
                "db_table": "bird_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarrierType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportation Carrier Type",
                "verbose_name_plural": "Transportation Carrier Types",
                "db_table": "carrier_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Currency Transaction ISO Code",
                "verbose_name_plural": "Financial Currency Transaction ISO Codes",
                "db_table": "currency_code",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Market Classification Segment",
                "verbose_name_plural": "Customer Market Classification Segments",
                "db_table": "customer_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiseaseOutbreakStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Epidemiological Outbreak Status",
                "verbose_name_plural": "Epidemiological Outbreak Statuses",
                "db_table": "disease_outbreak_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment Classification Type",
                "verbose_name_plural": "Employment Classification Types",
                "db_table": "employee_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventBookingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitality Event Reservation Status",
                "verbose_name_plural": "Hospitality Event Reservation Statuses",
                "db_table": "event_booking_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FarmBlockStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agricultural Farm Block Rest Status",
                "verbose_name_plural": "Agricultural Farm Block Rest Statuses",
                "db_table": "farm_block_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FarmVehicleType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Vehicle Type",
                "verbose_name_plural": "Farm Vehicle Types",
                "db_table": "farm_vehicle_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FatLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primal Meat Lipid/Fat Quality Grading Level",
                "verbose_name_plural": "Primal Meat Lipid/Fat Quality Grading Levels",
                "db_table": "fat_level",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedSourceChoices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Source",
                "verbose_name_plural": "Feed Sources",
                "db_table": "feed_source",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlockBatchStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch Production Status",
                "verbose_name_plural": "Flock Batch Production Statuses",
                "db_table": "flock_batch_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthRecordType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Health Intervention Record Type",
                "verbose_name_plural": "Clinical Health Intervention Record Types",
                "db_table": "health_record_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdentityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Type Documentation",
                "verbose_name_plural": "Identity Type Documentations",
                "db_table": "Identity_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncubationCycleStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubation Cycle Step Status",
                "verbose_name_plural": "Incubation Cycle Step Statuses",
                "db_table": "incubation_cycle_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncubatorMachineType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubator Machine Configuration Type",
                "verbose_name_plural": "Incubator Machine Configuration Types",
                "db_table": "incubator_machine_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemDisposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Item Return Disposition",
                "verbose_name_plural": "Customer Item Return Dispositions",
                "db_table": "item_disposition",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeatCutType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carcass Commercial Meat Cut Selection",
                "verbose_name_plural": "Carcass Commercial Meat Cut Selections",
                "db_table": "meat_cut_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Status Definition",
                "verbose_name_plural": "Order Status Definitions",
                "db_table": "order_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PackageStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Warehouse Inventory Status",
                "verbose_name_plural": "Package Warehouse Inventory Statuses",
                "db_table": "package_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Payment Channel Settlement Method",
                "verbose_name_plural": "Accounting Payment Channel Settlement Methods",
                "db_table": "payment_method",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Product Category",
                "verbose_name_plural": "Inventory Product Categories",
                "db_table": "product_category",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agronomy Crop Production Status",
                "verbose_name_plural": "Agronomy Crop Production Statuses",
                "db_table": "production_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RateType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logistics Valuation Service Rate Billing Type",
                "verbose_name_plural": "Logistics Valuation Service Rate Billing Types",
                "db_table": "rate_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistrationStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Status",
                "verbose_name_plural": "Registration Statuses",
                "db_table": "registration_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalUnitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Housing Property Unit Grid Type",
                "verbose_name_plural": "Commercial Housing Property Unit Grid Types",
                "db_table": "rental_unit_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SaleInvoiceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Sales Invoice Accounting Status",
                "verbose_name_plural": "Commercial Sales Invoice Accounting Statuses",
                "db_table": "sale_invoice_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShippingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping/Logistics Status",
                "verbose_name_plural": "Shipping/Logistics Statuses",
                "db_table": "shipping_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Procurement Origin Source",
                "verbose_name_plural": "Resource Procurement Origin Sources",
                "db_table": "source_choice",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeciesType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Biological Species Type",
                "verbose_name_plural": "Animal Biological Species Types",
                "db_table": "species_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovementType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction Movement Type",
                "verbose_name_plural": "Stock Transaction Movement Types",
                "db_table": "stock_movement_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockReadinessStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Market Readiness Status",
                "verbose_name_plural": "Stock Market Readiness Statuses",
                "db_table": "stock_readness_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thermal Preservation Storage State",
                "verbose_name_plural": "Thermal Preservation Storage States",
                "db_table": "storage_state",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageUnitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Unit Infrastructure Placement",
                "verbose_name_plural": "Storage Unit Infrastructure Placements",
                "db_table": "storage_unit_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskPriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Facility Task Execution Priority",
                "verbose_name_plural": "Operational Facility Task Execution Priorities",
                "db_table": "task_priority",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Task/Support Ticket Lifecycle Status",
                "verbose_name_plural": "Operational Task/Support Ticket Lifecycle Statuses",
                "db_table": "ticket_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Standardized Unit of Measure (UOM)",
                "verbose_name_plural": "Inventory Standardized Units of Measure (UOM)",
                "db_table": "unit_of_measure",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserTitle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Title",
                "verbose_name_plural": "User Titles",
                "db_table": "user_title",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WasteDisposalMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bio-Waste Management Disposal Method",
                "verbose_name_plural": "Bio-Waste Management Disposal Methods",
                "db_table": "waste_disposal_method",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BreedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Programmatic slug key used strictly in backend code logic conditions.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unique Immutable Handle Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Operational Description/UI Tooltip"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#7F8C8D",
                        max_length=7,
                        verbose_name="Frontend Theme Hex Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        verbose_name="Execution Sequencing Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Active State Configuration Visibility",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeds",
                        to="config.speciestype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Genetic Breed Variant",
                "verbose_name_plural": "Animal Genetic Breed Variants",
                "db_table": "breed_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
