# Generated by Django 6.0.2 on 2026-03-22 11:37

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("billing", "Billing"),
                            ("home", "Home"),
                            ("work", "Work"),
                        ],
                        default="shipping",
                        max_length=20,
                        verbose_name="Address Type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
                ("street_address", models.TextField(verbose_name="Street Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="State/Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "user_address",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Flexible JSON object storing user preferences.",
                        verbose_name="Preferences",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preference",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["preferences"], name="preferences_gin_idx"
                    )
                ],
            },
        ),
    ]
