# Generated by Django 6.0.2 on 2026-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_register_staff", "Can register a new staff user"),
                    (
                        "can_reset_password_other_user",
                        "Can force reset any user's password",
                    ),
                    (
                        "can_deactivate_user",
                        "Can deactivate any user account (is_active = False)",
                    ),
                    ("can_toggle_is_staff", "Can change a user's is_staff status"),
                    ("can_change_self_password", "Can reset individual password"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "System Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Last Name"
            ),
        ),
    ]
