# Generated by Django 6.0.2 on 2026-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_options_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="useraddress",
            constraint=models.UniqueConstraint(
                fields=("user", "address_type"), name="unique_user_address_type"
            ),
        ),
    ]
