# Generated by Django 6.0.2 on 2026-04-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_useraddress_unique_user_address_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="useraddress",
            name="unique_user_address_type",
        ),
        migrations.AlterUniqueTogether(
            name="useraddress",
            unique_together={("user", "address_type")},
        ),
    ]
