import logging
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_migrate
from django.dispatch import receiver
from common.permissions.config import PERM_CONFIG

logger = logging.getLogger(__name__)

@receiver(post_migrate)
def sync_enterprise_infrastructure(sender, **kwargs):
    """
    Executed on system migration deployment. Guarantees all custom non-CRUD verbs
    and functional system corporate Groups exist seamlessly in the database schema.

    - Dynamically fetch the current app config to prevent hardcoded string dependencies
    - Ensure this only executes for the app defining the models
    - Guarantee Group Existence
    - check, Is it a standard CRUD action generated by Django automatically?
    - Dynamically register custom verbs (e.g. 'can_register_staff') in the DB
    - Assign the permission globally to the group for standard model-level access
    - Invalidate runtime memory cache to force reloading fresh data post-migration
    """
    app_config = sender

    # Angalia kama app hii ndio iliyobeba mifano ya mifumo yetu kwenye PERM_CONFIG
    if not any(model_name in app_config.models for model_name in PERM_CONFIG.keys()):
        return

    logger.info("Initializing Enterprise Security Matrix Provisioning...")

    for model_name, roles in PERM_CONFIG.items():
        try:
            model_class = app_config.get_model(model_name)
            content_type = ContentType.objects.get_for_model(model_class)
        except LookupError:
            continue

        for role_name, permissions in roles.items():
            # Inatengeneza Group kama halipo mapema kabisa kwenye mfumo
            group, _ = Group.objects.get_or_create(name=role_name)

            for perm_codename in permissions:
                is_standard = any(
                    perm_codename.startswith(v)
                    for v in ["add_", "change_", "delete_", "view_"]
                )

                # Kama si ruhusa ya kawaida ya Django, isajili kama custom verb
                if not is_standard:
                    human_name = perm_codename.replace("_", " ").capitalize()
                    Permission.objects.get_or_create(
                        codename=perm_codename,
                        content_type=content_type,
                        defaults={"name": human_name},
                    )

                try:
                    perm_obj = Permission.objects.get(
                        codename=perm_codename, content_type=content_type
                    )
                    group.permissions.add(perm_obj)
                except Permission.DoesNotExist:
                    pass

    logger.info("Enterprise Security Matrix successfully synced.")
