# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Product Name"
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Product Specifications"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Quantity on Hand",
                    ),
                ),
                (
                    "minimum_stock_level",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minimum Stock Level"
                    ),
                ),
                (
                    "storage_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Target Storage Temp (°C)",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Batch Number",
                    ),
                ),
                (
                    "stock_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Stock Metadata"
                    ),
                ),
                (
                    "last_inspected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "product_stock",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="SKU / Item Code",
                    ),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=12, verbose_name="Unit Price"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is Available for Sale"
                    ),
                ),
                (
                    "variant_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Variant Metadata"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "db_table": "product_variant",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "quantity_change",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "units_change",
                    models.IntegerField(
                        default=0,
                        help_text="Idadi ya pakiti zilizopungua au kuongezeka (mf. -1, +10)",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "is_reversible",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this movement can be rolled back (e.g., for order cancellations).",
                        verbose_name="Is Reversible",
                    ),
                ),
                ("movement_metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "stock_movement",
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(max_length=20, verbose_name="Unit Code"),
                ),
                (
                    "max_capacity",
                    models.IntegerField(default=0, verbose_name="Max Capacity"),
                ),
            ],
            options={
                "verbose_name": "Storage Unit",
                "db_table": "storage_unit",
            },
        ),
        migrations.CreateModel(
            name="WarehouseLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("postcode", models.CharField(db_index=True, max_length=5)),
                ("address_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Location Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Warehouse Code"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Warehouse",
                "db_table": "warehouse_location",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Zone Name")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Zone Code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "db_table": "warehouse_zone",
            },
        ),
        migrations.CreateModel(
            name="PackagedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "production_line",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Kitambulisho cha mstari wa uzalishaji/usindikaji. Husaidia kufuatilia ufanisi wa mashine na timu iliyokuwa zamu.",
                        max_length=50,
                        verbose_name="Production Line",
                    ),
                ),
                (
                    "label_code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="QR/Barcode",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Unit Weight (KG)",
                    ),
                ),
                (
                    "units_inside_package",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Pieces Inside Package"
                    ),
                ),
                (
                    "packaging_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Stores material types, seal checks, and storage conditions.",
                        verbose_name="Packaging Specs",
                    ),
                ),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Packaged Product",
                "db_table": "packaged_product",
            },
        ),
    ]
