# Generated by Django 6.0.2 on 2026-06-06 15:35

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ppms", "0002_processingsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Product Name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EGG", "Eggs"),
                            ("MEAT", "Meat/Poultry"),
                            ("BY_PRODUCT", "By-Products (Manure/Feathers)"),
                            ("EQUIPMENT", "Farm Equipment/Assets"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Product Specifications"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "cut_type",
                    models.CharField(
                        choices=[
                            ("SLICE", "Slice / Steak (Lidandi / Shaba)"),
                            (
                                "PART",
                                "Primal Part / Cut (Sehemu ya Mnyama - mf. Paja, Mbavu)",
                            ),
                            (
                                "PIECE",
                                "Countable Piece (Idadi - mf. Soseji, Mishikaki)",
                            ),
                            (
                                "WHOLE",
                                "Whole Carcass / Bird (Mzoga Mzima / Kuku Mzima)",
                            ),
                        ],
                        default="WHOLE",
                        max_length=20,
                        verbose_name="Cut Type",
                    ),
                ),
                (
                    "storage_state",
                    models.CharField(
                        choices=[("FRESH", "Fresh / Chilled"), ("FROZEN", "Frozen")],
                        default="FRESH",
                        max_length=20,
                        verbose_name="Storage State",
                    ),
                ),
                (
                    "fat_level",
                    models.CharField(
                        choices=[
                            ("LEAN", "Lean / Low Fat"),
                            ("MEDIUM", "Medium Fat"),
                            ("HIGH", "High Fat / Premium Marbled"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Fat Content",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="SKU / Item Code",
                    ),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=12, verbose_name="Unit Price"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is Available for Sale"
                    ),
                ),
                (
                    "variant_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Variant Metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="ipss.product",
                        verbose_name="Parent Product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "db_table": "product_variant",
            },
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Quantity on Hand",
                    ),
                ),
                (
                    "minimum_stock_level",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minimum Stock Level"
                    ),
                ),
                (
                    "storage_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Target Storage Temp (°C)",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("TRAY", "Tray (Treya)"),
                            ("KG", "Kilogram (Kilogramu)"),
                            ("LITER", "Liter (Lita)"),
                            ("PCS", "Pieces (Idadi/Vipande)"),
                            ("BAG", "Bag (Mfuko)"),
                            ("BOX", "Box (Boxi)"),
                        ],
                        max_length=20,
                        verbose_name="Unit Of Measure",
                    ),
                ),
                (
                    "readiness_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready for Sale"),
                            ("NOT_READY", "Not Ready / WIP"),
                            ("QUARANTINE", "Under Inspection"),
                            ("EXPIRED", "Expired / Waste"),
                        ],
                        default="READY",
                        max_length=20,
                        verbose_name="Readiness",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Batch Number",
                    ),
                ),
                (
                    "stock_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Stock Metadata"
                    ),
                ),
                (
                    "last_inspected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_stock",
                        to="ipss.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "product_stock",
            },
        ),
        migrations.CreateModel(
            name="PackagedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "production_line",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Kitambulisho cha mstari wa uzalishaji/usindikaji. Husaidia kufuatilia ufanisi wa mashine na timu iliyokuwa zamu.",
                        max_length=50,
                        verbose_name="Production Line",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "Ipo Ghalani"),
                            ("SOLD", "Imeuzwa"),
                            ("SPOILED", "Imeharibika/Imeoza"),
                            ("TRANSFERRED", "Imehamishwa Banda/Ghala"),
                        ],
                        db_index=True,
                        default="IN_STOCK",
                        max_length=20,
                    ),
                ),
                (
                    "label_code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="QR/Barcode",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Unit Weight (KG)",
                    ),
                ),
                (
                    "units_inside_package",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Pieces Inside Package"
                    ),
                ),
                (
                    "packaging_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Stores material types, seal checks, and storage conditions.",
                        verbose_name="Packaging Specs",
                    ),
                ),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="ppms.processingsession",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="ipss.productvariant",
                        verbose_name="Product Variant Reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packaged Product",
                "db_table": "packaged_product",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("RETURN", "Return"),
                            ("RESTOCK", "Restock"),
                            ("ADJUST", "Adjustment"),
                            ("TRANSFER", "Internal Transfer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "quantity_change",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "units_change",
                    models.IntegerField(
                        default=0,
                        help_text="Idadi ya pakiti zilizopungua au kuongezeka (mf. -1, +10)",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "is_reversible",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this movement can be rolled back (e.g., for order cancellations).",
                        verbose_name="Is Reversible",
                    ),
                ),
                ("movement_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="ipss.productstock",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_movement",
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(max_length=20, verbose_name="Unit Code"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("SHELF", "Shelf (Rafu)"),
                            ("KABATI", "Cabinet (Kabati)"),
                            ("CLIPBOARD", "Clipboard"),
                            ("DRAWER", "Drawer (Droo)"),
                            ("COLD_ROOM", "Cold Room Rack"),
                        ],
                        default="SHELF",
                        max_length=20,
                        verbose_name="Storage Mean",
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(default=0, verbose_name="Max Capacity"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Unit",
                "db_table": "storage_unit",
            },
        ),
        migrations.AddField(
            model_name="productstock",
            name="storage_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_items",
                to="ipss.storageunit",
            ),
        ),
        migrations.CreateModel(
            name="WarehouseLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("postcode", models.CharField(db_index=True, max_length=5)),
                ("address_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Location Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Warehouse Code"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "db_table": "warehouse_location",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Zone Name")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Zone Code"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="ipss.warehouselocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "db_table": "warehouse_zone",
            },
        ),
        migrations.AddField(
            model_name="storageunit",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_units",
                to="ipss.zone",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["specs"], name="product_specs_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "cut_type", "storage_state", "fat_level")},
        ),
        migrations.AddIndex(
            model_name="packagedproduct",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["packaging_metadata"], name="package_meta_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["movement_metadata"], name="stock_move_meta_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["stock_metadata"], name="stock_meta_gin_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productstock",
            unique_together={
                ("product_type", "storage_unit", "readiness_status", "batch_number")
            },
        ),
        migrations.AlterUniqueTogether(
            name="storageunit",
            unique_together={("zone", "unit_code")},
        ),
    ]
