# Generated by Django 6.0.2 on 2026-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipss", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedproduct",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="storageunit",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="warehouselocation",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="updated_on",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
    ]
