PERM_CONFIG = {

    'User': {
        'Chief Executive Officer': ['add_user', 'change_user', 'delete_user', 'view_user', 'can_register_staff', 'can_reset_password_other_user', 'can_deactivate_user', 'can_toggle_is_staff', 'can_change_self_password'],
        'System Administrator': ['add_user', 'change_user', 'delete_user', 'view_user', 'can_register_staff', 'can_reset_password_other_user', 'can_deactivate_user', 'can_toggle_is_staff', 'can_change_self_password'],
        'Human Resource Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Human Resource Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Farm Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Transport Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Transport Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Sanitation and Waster Supervisor': ['view_user', 'change_user', 'can_change_self_password'],
        'Sanitation and Waster Supervisor': ['view_user', 'change_user', 'can_change_self_password'],
        'Recruitment Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Content Creator': ['view_user', 'change_user', 'can_change_self_password'],
        'Digital Platform and Community Cordinator': ['view_user', 'change_user', 'can_change_self_password'],
        'Security and Bio-exclusion Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Decollation Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Security and Bio-exclusion Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Receptionist': ['add_user', 'view_user', 'change_user', 'can_change_self_password'],
        'Ground and Greenery Keeper': ['view_user', 'change_user', 'can_change_self_password'],
        'Playground and Leisure Supervisor': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Ground and Greenery Keeper': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Playground and Leisure Supervisor': ['view_user', 'change_user', 'can_change_self_password'],
        'Senior Maintainance Engineer': ['view_user', 'change_user', 'can_change_self_password'],
        'Maintainance Engineer': ['view_user', 'change_user', 'can_change_self_password'],
        'Housing and Apartment Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Housing and Apartment Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Sales Agent': ['view_user', 'change_user', 'can_change_self_password'],
        'Marketing Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Derivery and Sales Agent': ['view_user', 'change_user', 'can_change_self_password'],
        'Packaging Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Processing Plant Supervisor': ['view_user', 'change_user', 'can_change_self_password'],
        'Senior Chef': ['view_user', 'change_user', 'can_change_self_password'],
        'Chef': ['view_user', 'change_user', 'can_change_self_password'],
        'Flock and Shed Attendant': ['view_user', 'change_user', 'can_change_self_password'],
        'Incubation and Hatchery Specialist': ['view_user', 'change_user', 'can_change_self_password'],
        'Customer': ['add_user', 'view_user', 'change_user', 'delete_user', 'can_change_self_password'],
        'Nutritionist': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Nutritionist': ['view_user', 'change_user', 'can_change_self_password'],
        'Veterinary Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'Lead Veterinary Officer': ['view_user', 'change_user', 'can_change_self_password'],
        'General Farm Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Farm Manager': ['view_user', 'change_user', 'can_change_self_password'],
        'Treasurer': ['view_user', 'change_user', 'can_change_self_password'],
        'Visitor': ['add_user', 'view_user', 'change_user', 'can_change_self_password'],
        'Tenant': ['add_user', 'view_user', 'change_user', 'can_change_self_password'],
    },
    'UserAddress': {
        'Chief Executive Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'System Administrator': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Human Resource Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Human Resource Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Farm Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Transport Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Transport Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Sanitation and Waster Supervisor': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Sanitation and Waster Supervisor': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Recruitment Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Content Creator': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Digital Platform and Community Cordinator': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Security and Bio-exclusion Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Decollation Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Security and Bio-exclusion Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Receptionist': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Ground and Greenery Keeper': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Playground and Leisure Supervisor': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Ground and Greenery Keeper': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Playground and Leisure Supervisor': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Senior Maintainance Engineer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Maintainance Engineer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Housing and Apartment Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Housing and Apartment Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Sales Agent': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Marketing Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Derivery and Sales Agent': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Packaging Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Processing Plant Supervisor': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Senior Chef': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Chef': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Flock and Shed Attendant': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Incubation and Hatchery Specialist': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Customer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Nutritionist': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Nutritionist': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Veterinary Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Lead Veterinary Officer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'General Farm Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Farm Manager': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Treasurer': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Visitor': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
        'Tenant': ['add_user_address', 'change_user_address', 'delete_user_address', 'view_user_address'],
    },
    'UserPreference': {
        'Chief Executive Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'System Administrator': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Human Resource Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Human Resource Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Farm Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Transport Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Transport Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Sanitation and Waster Supervisor': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Sanitation and Waster Supervisor': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Recruitment Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Content Creator': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Digital Platform and Community Cordinator': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Security and Bio-exclusion Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Decollation Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Security and Bio-exclusion Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Receptionist': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Ground and Greenery Keeper': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Playground and Leisure Supervisor': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Ground and Greenery Keeper': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Playground and Leisure Supervisor': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Senior Maintainance Engineer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Maintainance Engineer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Housing and Apartment Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Housing and Apartment Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Sales Agent': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Marketing Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Derivery and Sales Agent': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Packaging Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Processing Plant Supervisor': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Senior Chef': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Chef': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Flock and Shed Attendant': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Incubation and Hatchery Specialist': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Customer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Nutritionist': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Nutritionist': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Veterinary Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Lead Veterinary Officer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'General Farm Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Farm Manager': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Treasurer': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Visitor': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
        'Tenant': ['add_user_preference', 'change_user_preference', 'delete_user_preference', 'view_user_preference'],
    },
    'UserActivityLog': {
        'Chief Executive Officer': ['view_activity_log'],
        'System Administrator': ['view_activity_log'],
        'Human Resource Officer': ['view_activity_log'],
        'Human Resource Manager': ['view_activity_log'],
        'Farm Manager': ['view_activity_log'],
        'Transport Officer': ['view_activity_log'],
        'Lead Transport Officer': ['view_activity_log'],
        'Lead Sanitation and Waster Supervisor': ['view_activity_log'],
        'Sanitation and Waster Supervisor': ['view_activity_log'],
        'Recruitment Manager': ['view_activity_log'],
        'Content Creator': ['view_activity_log'],
        'Digital Platform and Community Cordinator': ['view_activity_log'],
        'Security and Bio-exclusion Officer': ['view_activity_log'],
        'Decollation Officer': ['view_activity_log'],
        'Security and Bio-exclusion Officer': ['view_activity_log'],
        'Receptionist': ['view_activity_log'],
        'Ground and Greenery Keeper': ['view_activity_log'],
        'Playground and Leisure Supervisor': ['view_activity_log'],
        'Lead Ground and Greenery Keeper': ['view_activity_log'],
        'Lead Playground and Leisure Supervisor': ['view_activity_log'],
        'Senior Maintainance Engineer': ['view_activity_log'],
        'Maintainance Engineer': ['view_activity_log'],
        'Housing and Apartment Manager': ['view_activity_log'],
        'Lead Housing and Apartment Manager': ['view_activity_log'],
        'Sales Agent': ['view_activity_log'],
        'Marketing Manager': ['view_activity_log'],
        'Derivery and Sales Agent': ['view_activity_log'],
        'Packaging Manager': ['view_activity_log'],
        'Processing Plant Supervisor': ['view_activity_log'],
        'Senior Chef': ['view_activity_log'],
        'Chef': ['view_activity_log'],
        'Flock and Shed Attendant': ['view_activity_log'],
        'Incubation and Hatchery Specialist': ['view_activity_log'],
        'Customer': ['view_activity_log'],
        'Nutritionist': ['view_activity_log'],
        'Lead Nutritionist': ['view_activity_log'],
        'Veterinary Officer': ['view_activity_log'],
        'Lead Veterinary Officer': ['view_activity_log'],
        'General Farm Manager': ['view_activity_log'],
        'Farm Manager': ['view_activity_log'],
        'Treasurer': ['view_activity_log'],
        'Visitor': ['view_activity_log'],
        'Tenant': ['view_activity_log'],
    },
    'SearchHistory': {
        'Chief Executive Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'System Administrator': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Human Resource Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Human Resource Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Farm Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Transport Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Transport Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Sanitation and Waster Supervisor': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Sanitation and Waster Supervisor': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Recruitment Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Content Creator': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Digital Platform and Community Cordinator': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Security and Bio-exclusion Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Decollation Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Security and Bio-exclusion Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Receptionist': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Ground and Greenery Keeper': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Playground and Leisure Supervisor': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Ground and Greenery Keeper': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Playground and Leisure Supervisor': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Senior Maintainance Engineer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Maintainance Engineer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Housing and Apartment Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Housing and Apartment Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Sales Agent': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Marketing Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Derivery and Sales Agent': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Packaging Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Processing Plant Supervisor': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Senior Chef': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Chef': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Flock and Shed Attendant': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Incubation and Hatchery Specialist': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Customer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Nutritionist': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Nutritionist': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Veterinary Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Lead Veterinary Officer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'General Farm Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Farm Manager': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Treasurer': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Visitor': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
        'Tenant': ['add_user_search_history', 'delete_user_search_history', 'view_user_search_history'],
    },
    'UserInterest': {
        'Chief Executive Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'System Administrator': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Human Resource Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Human Resource Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Farm Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Transport Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Transport Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Sanitation and Waster Supervisor': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Sanitation and Waster Supervisor': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Recruitment Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Content Creator': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Digital Platform and Community Cordinator': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Security and Bio-exclusion Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Decollation Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Security and Bio-exclusion Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Receptionist': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Ground and Greenery Keeper': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Playground and Leisure Supervisor': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Ground and Greenery Keeper': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Playground and Leisure Supervisor': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Senior Maintainance Engineer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Maintainance Engineer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Housing and Apartment Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Housing and Apartment Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Sales Agent': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Marketing Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Derivery and Sales Agent': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Packaging Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Processing Plant Supervisor': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Senior Chef': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Chef': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Flock and Shed Attendant': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Incubation and Hatchery Specialist': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Customer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Nutritionist': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Nutritionist': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Veterinary Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Lead Veterinary Officer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'General Farm Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Farm Manager': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Treasurer': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Visitor': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
        'Tenant': ['add_user_interests', 'change_user_interests', 'delete_user_interests', 'view_user_interests'],
    },
    'Wishlist': {
        'Chief Executive Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'System Administrator': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Human Resource Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Human Resource Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Farm Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Transport Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Transport Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Sanitation and Waster Supervisor': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Sanitation and Waster Supervisor': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Recruitment Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Content Creator': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Digital Platform and Community Cordinator': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Security and Bio-exclusion Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Decollation Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Security and Bio-exclusion Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Receptionist': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Ground and Greenery Keeper': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Playground and Leisure Supervisor': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Ground and Greenery Keeper': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Playground and Leisure Supervisor': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Senior Maintainance Engineer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Maintainance Engineer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Housing and Apartment Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Housing and Apartment Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Sales Agent': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Marketing Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Derivery and Sales Agent': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Packaging Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Processing Plant Supervisor': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Senior Chef': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Chef': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Flock and Shed Attendant': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Incubation and Hatchery Specialist': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Customer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Nutritionist': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Nutritionist': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Veterinary Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Lead Veterinary Officer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'General Farm Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Farm Manager': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Treasurer': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Visitor': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
        'Tenant': ['add_user_wishlist', 'change_user_wishlist', 'delete_user_wishlist', 'view_user_wishlist'],
    },
    'NextOfKin': {
        'Chief Executive Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'System Administrator': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Human Resource Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Human Resource Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Farm Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Transport Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Transport Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Sanitation and Waster Supervisor': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Sanitation and Waster Supervisor': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Recruitment Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Content Creator': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Digital Platform and Community Cordinator': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Security and Bio-exclusion Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Decollation Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Security and Bio-exclusion Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Receptionist': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Ground and Greenery Keeper': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Playground and Leisure Supervisor': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Ground and Greenery Keeper': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Playground and Leisure Supervisor': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Senior Maintainance Engineer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Maintainance Engineer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Housing and Apartment Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Housing and Apartment Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Sales Agent': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Marketing Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Derivery and Sales Agent': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Packaging Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Processing Plant Supervisor': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Senior Chef': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Chef': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Flock and Shed Attendant': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Incubation and Hatchery Specialist': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Nutritionist': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Nutritionist': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Veterinary Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Lead Veterinary Officer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'General Farm Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Farm Manager': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Treasurer': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
        'Tenant': ['add_next_of_kin', 'change_next_of_kin', 'delete_next_of_kin', 'view_next_of_kin'],
    },
    'ShoppingCart': {
        'Chief Executive Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'System Administrator': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Human Resource Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Human Resource Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Farm Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Transport Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Transport Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Sanitation and Waster Supervisor': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Sanitation and Waster Supervisor': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Recruitment Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Content Creator': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Digital Platform and Community Cordinator': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Security and Bio-exclusion Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Decollation Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Security and Bio-exclusion Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Receptionist': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Ground and Greenery Keeper': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Playground and Leisure Supervisor': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Ground and Greenery Keeper': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Playground and Leisure Supervisor': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Senior Maintainance Engineer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Maintainance Engineer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Housing and Apartment Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Housing and Apartment Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Sales Agent': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Marketing Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Derivery and Sales Agent': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Packaging Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Processing Plant Supervisor': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Senior Chef': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Chef': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Flock and Shed Attendant': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Incubation and Hatchery Specialist': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Customer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Nutritionist': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Nutritionist': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Veterinary Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Lead Veterinary Officer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'General Farm Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Farm Manager': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Treasurer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Visitor': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Customer': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
        'Tenant': ['add_cart', 'change_cart', 'delete_cart', 'view_cart'],
    },
    'ShoppingCartItem': {
        'Chief Executive Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'System Administrator': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Human Resource Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Human Resource Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Farm Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Transport Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Transport Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Sanitation and Waster Supervisor': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Sanitation and Waster Supervisor': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Recruitment Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Content Creator': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Digital Platform and Community Cordinator': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Security and Bio-exclusion Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Decollation Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Security and Bio-exclusion Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Receptionist': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Ground and Greenery Keeper': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Playground and Leisure Supervisor': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Ground and Greenery Keeper': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Playground and Leisure Supervisor': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Senior Maintainance Engineer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Maintainance Engineer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Housing and Apartment Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Housing and Apartment Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Sales Agent': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Marketing Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Derivery and Sales Agent': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Packaging Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Processing Plant Supervisor': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Senior Chef': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Chef': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Flock and Shed Attendant': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Incubation and Hatchery Specialist': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Customer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Nutritionist': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Nutritionist': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Veterinary Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Lead Veterinary Officer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'General Farm Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Farm Manager': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Treasurer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Visitor': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Customer': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
        'Tenant': ['add_shopping_cart_item', 'change_shopping_cart_item', 'delete_shopping_cart_item', 'view_shopping_cart_item'],
    },
    'RecentlyViewedItem': {
        'Chief Executive Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'System Administrator': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Human Resource Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Human Resource Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Farm Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Transport Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Transport Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Sanitation and Waster Supervisor': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Sanitation and Waster Supervisor': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Recruitment Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Content Creator': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Digital Platform and Community Cordinator': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Security and Bio-exclusion Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Decollation Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Security and Bio-exclusion Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Receptionist': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Ground and Greenery Keeper': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Playground and Leisure Supervisor': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Ground and Greenery Keeper': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Playground and Leisure Supervisor': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Senior Maintainance Engineer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Maintainance Engineer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Housing and Apartment Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Housing and Apartment Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Sales Agent': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Marketing Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Derivery and Sales Agent': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Packaging Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Processing Plant Supervisor': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Senior Chef': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Chef': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Flock and Shed Attendant': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Incubation and Hatchery Specialist': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Customer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Nutritionist': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Nutritionist': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Veterinary Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Lead Veterinary Officer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'General Farm Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Farm Manager': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Treasurer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Visitor': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Customer': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
        'Tenant': ['add_user_recently_viewed', 'change_user_recently_viewed', 'delete_user_recently_viewed', 'view_user_recently_viewed'],
    },
    'Review': {
        'Chief Executive Officer': ['add_product_review', 'view_product_review'],
        'System Administrator': ['add_product_review', 'view_product_review'],
        'Human Resource Officer': ['add_product_review', 'view_product_review'],
        'Human Resource Manager': ['add_product_review', 'view_product_review'],
        'Farm Manager': ['add_product_review', 'view_product_review'],
        'Transport Officer': ['add_product_review', 'view_product_review'],
        'Lead Transport Officer': ['add_product_review', 'view_product_review'],
        'Lead Sanitation and Waster Supervisor': ['add_product_review', 'view_product_review'],
        'Sanitation and Waster Supervisor': ['add_product_review', 'view_product_review'],
        'Recruitment Manager': ['add_product_review', 'view_product_review'],
        'Content Creator': ['add_product_review', 'view_product_review'],
        'Digital Platform and Community Cordinator': ['add_product_review', 'view_product_review'],
        'Security and Bio-exclusion Officer': ['add_product_review', 'view_product_review'],
        'Decollation Officer': ['add_product_review', 'view_product_review'],
        'Security and Bio-exclusion Officer': ['add_product_review', 'view_product_review'],
        'Receptionist': ['add_product_review', 'view_product_review'],
        'Ground and Greenery Keeper': ['add_product_review', 'view_product_review'],
        'Playground and Leisure Supervisor': ['add_product_review', 'view_product_review'],
        'Lead Ground and Greenery Keeper': ['add_product_review', 'view_product_review'],
        'Lead Playground and Leisure Supervisor': ['add_product_review', 'view_product_review'],
        'Senior Maintainance Engineer': ['add_product_review', 'view_product_review'],
        'Maintainance Engineer': ['add_product_review', 'view_product_review'],
        'Housing and Apartment Manager': ['add_product_review', 'view_product_review'],
        'Lead Housing and Apartment Manager': ['add_product_review', 'view_product_review'],
        'Sales Agent': ['add_product_review', 'view_product_review'],
        'Marketing Manager': ['add_product_review', 'view_product_review'],
        'Derivery and Sales Agent': ['add_product_review', 'view_product_review'],
        'Packaging Manager': ['add_product_review', 'view_product_review'],
        'Processing Plant Supervisor': ['add_product_review', 'view_product_review'],
        'Senior Chef': ['add_product_review', 'view_product_review'],
        'Chef': ['add_product_review', 'view_product_review'],
        'Flock and Shed Attendant': ['add_product_review', 'view_product_review'],
        'Incubation and Hatchery Specialist': ['add_product_review', 'view_product_review'],
        'Customer': ['add_product_review', 'view_product_review'],
        'Nutritionist': ['add_product_review', 'view_product_review'],
        'Lead Nutritionist': ['add_product_review', 'view_product_review'],
        'Veterinary Officer': ['add_product_review', 'view_product_review'],
        'Lead Veterinary Officer': ['add_product_review', 'view_product_review'],
        'General Farm Manager': ['add_product_review', 'view_product_review'],
        'Farm Manager': ['add_product_review', 'view_product_review'],
        'Treasurer': ['add_product_review', 'view_product_review'],
        'Visitor': ['add_product_review', 'view_product_review'],
        'Customer': ['add_product_review', 'view_product_review'],
        'Tenant': ['add_product_review', 'view_product_review'],
    },
    'FeedType': {
        'Chief Executive Officer': ['add_feed_type', 'delete_feed_type', 'view_feed_type', 'change_feed_type'],
        'Farm Manager': ['view_feed_type'],
        'Nutritionist': ['add_feed_type', 'delete_feed_type', 'view_feed_type', 'change_feed_type'],
        'Lead Nutritionist': ['add_feed_type', 'delete_feed_type', 'view_feed_type', 'change_feed_type'],
        'Veterinary Officer': ['view_feed_type'],
        'Lead Veterinary Officer': ['view_feed_type'],
        'General Farm Manager': ['view_feed_type'],
    },
    'FeedInventory': {
        'Chief Executive Officer': ['add_feed_inventory', 'delete_feed_inventory', 'view_feed_inventory', 'change_feed_inventory'],
        'Farm Manager': ['view_feed_inventory'],
        'Nutritionist': ['add_feed_inventory', 'delete_feed_inventory', 'view_feed_inventory', 'change_feed_inventory'],
        'Lead Nutritionist': ['add_feed_inventory', 'delete_feed_inventory', 'view_feed_inventory', 'change_feed_inventory'],
        'Veterinary Officer': ['view_feed_inventory'],
        'Lead Veterinary Officer': ['view_feed_inventory'],
        'General Farm Manager': ['view_feed_inventory'],
        'Treasurer': ['view_feed_inventory'],
    },
    'FeedConsumption': {
        'Chief Executive Officer': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption', 'view_kpi_dashboard'],
        'Farm Manager': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption', 'view_kpi_dashboard', 'update_water_intake'],
        'Nutritionist': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption', 'update_water_intake'],
        'Lead Nutritionist': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption', 'view_kpi_dashboard', 'update_water_intake'],
        'Veterinary Officer': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption'],
        'Lead Veterinary Officer': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption'],
        'General Farm Manager': ['add_feed_consumption', 'view_feed_consumption', 'change_feed_consumption', 'view_kpi_dashboard', 'update_water_intake'],
    },
    'UserIdentity': {
        'Chief Executive Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'System Administrator': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Human Resource Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Human Resource Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Farm Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Transport Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Transport Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Sanitation and Waster Supervisor': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Sanitation and Waster Supervisor': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Recruitment Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Content Creator': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Digital Platform and Community Cordinator': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Security and Bio-exclusion Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Decollation Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Security and Bio-exclusion Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Receptionist': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Ground and Greenery Keeper': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Playground and Leisure Supervisor': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Ground and Greenery Keeper': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Playground and Leisure Supervisor': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Senior Maintainance Engineer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Maintainance Engineer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Housing and Apartment Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Housing and Apartment Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Sales Agent': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Marketing Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Derivery and Sales Agent': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Packaging Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Processing Plant Supervisor': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Senior Chef': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Chef': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Flock and Shed Attendant': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Incubation and Hatchery Specialist': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Nutritionist': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Nutritionist': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Veterinary Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Lead Veterinary Officer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'General Farm Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Farm Manager': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Treasurer': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
        'Tenant': ['add_employee_identity', 'change_employee_identity', 'delete_employee_identity', 'view_employee_identity'],
    },
    'WorkShift': {
        'Chief Executive Officer': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'System Administrator': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Human Resource Officer': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Human Resource Manager': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Farm Manager': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Transport Officer': ['view_work_shift'],
        'Lead Transport Officer': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Lead Sanitation and Waster Supervisor': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Sanitation and Waster Supervisor': ['view_work_shift'],
        'Recruitment Manager': ['view_work_shift'],
        'Content Creator': ['view_work_shift'],
        'Digital Platform and Community Cordinator': ['view_work_shift'],
        'Security and Bio-exclusion Officer': ['view_work_shift'],
        'Decollation Officer': ['view_work_shift'],
        'Security and Bio-exclusion Officer': ['view_work_shift'],
        'Receptionist': ['view_work_shift'],
        'Ground and Greenery Keeper': ['view_work_shift'],
        'Playground and Leisure Supervisor': ['view_work_shift'],
        'Lead Ground and Greenery Keeper': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Lead Playground and Leisure Supervisor': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Senior Maintainance Engineer': ['view_work_shift'],
        'Maintainance Engineer': ['view_work_shift'],
        'Housing and Apartment Manager': ['view_work_shift'],
        'Lead Housing and Apartment Manager': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Sales Agent': ['view_work_shift'],
        'Marketing Manager': ['view_work_shift'],
        'Derivery and Sales Agent': ['view_work_shift'],
        'Packaging Manager': ['view_work_shift'],
        'Processing Plant Supervisor': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Senior Chef': ['add_work_shift', 'change_work_shift', 'delete_work_shift', 'view_work_shift'],
        'Chef': ['view_work_shift'],
        'Flock and Shed Attendant': ['view_work_shift'],
        'Incubation and Hatchery Specialist': ['view_work_shift'],
        'Nutritionist': ['view_work_shift'],
        'Lead Nutritionist': ['view_work_shift'],
        'Veterinary Officer': ['view_work_shift'],
        'Lead Veterinary Officer': ['view_work_shift'],
        'General Farm Manager': ['view_work_shift'],
        'Farm Manager': ['view_work_shift'],
        'Treasurer': ['view_work_shift'],
        'Tenant': ['view_work_shift'],
    },
    'PayrollRecord': {
        'Chief Executive Officer': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'System Administrator': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'Human Resource Officer': ['add_payroll_record', 'change_payroll_record', 'view_payroll_record'],
        'Human Resource Manager': ['add_payroll_record', 'change_payroll_record', 'view_payroll_record'],
        'Farm Manager': ['add_payroll_record', 'change_payroll_record', 'view_payroll_record'],
        'Transport Officer': ['view_payroll_record'],
        'Lead Transport Officer': ['add_payroll_record', 'change_payroll_record', 'view_payroll_record'],
        'Lead Sanitation and Waster Supervisor': ['add_payroll_record', 'change_payroll_record', 'view_payroll_record'],
        'Sanitation and Waster Supervisor': ['view_payroll_record'],
        'Recruitment Manager': ['view_payroll_record'],
        'Content Creator': ['view_payroll_record'],
        'Digital Platform and Community Cordinator': ['view_payroll_record'],
        'Security and Bio-exclusion Officer': ['view_payroll_record'],
        'Decollation Officer': ['view_payroll_record'],
        'Security and Bio-exclusion Officer': ['view_payroll_record'],
        'Receptionist': ['view_payroll_record'],
        'Ground and Greenery Keeper': ['view_payroll_record'],
        'Playground and Leisure Supervisor': ['view_payroll_record'],
        'Lead Ground and Greenery Keeper': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'Lead Playground and Leisure Supervisor': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'Senior Maintainance Engineer': ['view_payroll_record'],
        'Maintainance Engineer': ['view_payroll_record'],
        'Housing and Apartment Manager': ['view_payroll_record'],
        'Lead Housing and Apartment Manager': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'Sales Agent': ['view_payroll_record'],
        'Marketing Manager': ['view_payroll_record'],
        'Derivery and Sales Agent': ['view_payroll_record'],
        'Packaging Manager': ['view_payroll_record'],
        'Processing Plant Supervisor': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'Senior Chef': ['add_payroll_record', 'change_payroll_record', 'delete_payroll_record', 'view_payroll_record'],
        'Chef': ['view_payroll_record'],
        'Flock and Shed Attendant': ['view_payroll_record'],
        'Incubation and Hatchery Specialist': ['view_payroll_record'],
        'Nutritionist': ['view_payroll_record'],
        'Lead Nutritionist': ['view_payroll_record'],
        'Veterinary Officer': ['view_payroll_record'],
        'Lead Veterinary Officer': ['view_payroll_record'],
        'General Farm Manager': ['view_payroll_record'],
        'Farm Manager': ['view_payroll_record'],
        'Treasurer': ['add_payroll_record', 'change_payroll_record', 'view_payroll_record'],
    },
    'Building': {
        'Chief Executive Officer': ['add_building', 'view_building', 'change_building', 'delete_building'],
        'System Administrator': ['add_building', 'view_building', 'change_building', 'delete_building'],
        'Human Resource Officer': ['view_building'],
        'Human Resource Manager': ['view_building'],
        'Farm Manager': ['view_building'],
        'Transport Officer': ['view_building'],
        'Lead Transport Officer': ['view_building'],
        'Lead Sanitation and Waster Supervisor': ['view_building'],
        'Sanitation and Waster Supervisor': ['view_building'],
        'Recruitment Manager': ['view_building'],
        'Content Creator': ['view_building'],
        'Digital Platform and Community Cordinator': ['view_building'],
        'Security and Bio-exclusion Officer': ['view_building'],
        'Decollation Officer': ['view_building'],
        'Security and Bio-exclusion Officer': ['view_building'],
        'Receptionist': ['view_building'],
        'Ground and Greenery Keeper': ['view_building'],
        'Playground and Leisure Supervisor': ['view_building'],
        'Lead Ground and Greenery Keeper': ['view_building'],
        'Lead Playground and Leisure Supervisor': ['view_building'],
        'Senior Maintainance Engineer': ['view_building'],
        'Maintainance Engineer': ['view_building'],
        'Housing and Apartment Manager': ['add_building', 'view_building', 'change_building'],
        'Lead Housing and Apartment Manager': ['add_building', 'view_building', 'change_building'],
        'Sales Agent': ['view_building'],
        'Marketing Manager': ['view_building'],
        'Derivery and Sales Agent': ['view_building'],
        'Packaging Manager': ['view_building'],
        'Processing Plant Supervisor': ['view_building'],
        'Senior Chef': ['view_building'],
        'Chef': ['view_building'],
        'Flock and Shed Attendant': ['view_building'],
        'Incubation and Hatchery Specialist': ['view_building'],
        'Customer': ['view_building'],
        'Nutritionist': ['view_building'],
        'Lead Nutritionist': ['view_building'],
        'Veterinary Officer': ['view_building'],
        'Lead Veterinary Officer': ['view_building'],
        'General Farm Manager': ['view_building'],
        'Farm Manager': ['view_building'],
        'Treasurer': ['view_building'],
        'Visitor': ['view_building'],
        'Customer': ['view_building'],
        'Tenant': ['view_building'],
    },
    'RentalUnit': {
        'Chief Executive Officer': ['add_rental_unit', 'view_rental_unit', 'change_rental_unit', 'delete_rental_unit'],
        'System Administrator': ['add_rental_unit', 'view_rental_unit', 'change_rental_unit', 'delete_rental_unit'],
        'Human Resource Officer': ['view_rental_unit'],
        'Human Resource Manager': ['view_rental_unit'],
        'Farm Manager': ['view_rental_unit'],
        'Transport Officer': ['view_rental_unit'],
        'Lead Transport Officer': ['view_rental_unit'],
        'Lead Sanitation and Waster Supervisor': ['view_rental_unit'],
        'Sanitation and Waster Supervisor': ['view_rental_unit'],
        'Recruitment Manager': ['view_rental_unit'],
        'Content Creator': ['view_rental_unit'],
        'Digital Platform and Community Cordinator': ['view_rental_unit'],
        'Security and Bio-exclusion Officer': ['view_rental_unit'],
        'Decollation Officer': ['view_rental_unit'],
        'Security and Bio-exclusion Officer': ['view_rental_unit'],
        'Receptionist': ['view_rental_unit'],
        'Ground and Greenery Keeper': ['view_rental_unit'],
        'Playground and Leisure Supervisor': ['view_rental_unit'],
        'Lead Ground and Greenery Keeper': ['view_rental_unit'],
        'Lead Playground and Leisure Supervisor': ['view_rental_unit'],
        'Senior Maintainance Engineer': ['view_rental_unit'],
        'Maintainance Engineer': ['view_rental_unit'],
        'Housing and Apartment Manager': ['add_rental_unit', 'view_rental_unit', 'change_rental_unit'],
        'Lead Housing and Apartment Manager': ['add_rental_unit', 'view_rental_unit', 'change_rental_unit'],
        'Sales Agent': ['view_rental_unit'],
        'Marketing Manager': ['view_rental_unit'],
        'Derivery and Sales Agent': ['view_rental_unit'],
        'Packaging Manager': ['view_rental_unit'],
        'Processing Plant Supervisor': ['view_rental_unit'],
        'Senior Chef': ['view_rental_unit'],
        'Chef': ['view_rental_unit'],
        'Flock and Shed Attendant': ['view_rental_unit'],
        'Incubation and Hatchery Specialist': ['view_rental_unit'],
        'Customer': ['view_rental_unit'],
        'Nutritionist': ['view_rental_unit'],
        'Lead Nutritionist': ['view_rental_unit'],
        'Veterinary Officer': ['view_rental_unit'],
        'Lead Veterinary Officer': ['view_rental_unit'],
        'General Farm Manager': ['view_rental_unit'],
        'Farm Manager': ['view_rental_unit'],
        'Treasurer': ['view_rental_unit'],
        'Visitor': ['view_rental_unit'],
        'Customer': ['view_rental_unit'],
        'Tenant': ['view_rental_unit'],
    },
    'Tenant': {
        'Chief Executive Officer': ['add_tenant', 'view_tenant', 'change_tenant', 'delete_tenant'],
        'System Administrator': ['add_tenant', 'view_tenant', 'change_tenant', 'delete_tenant'],
        'Human Resource Officer': ['view_tenant'],
        'Human Resource Manager': ['view_tenant'],
        'Farm Manager': ['view_tenant'],
        'Transport Officer': ['view_tenant'],
        'Lead Transport Officer': ['view_tenant'],
        'Lead Sanitation and Waster Supervisor': ['view_tenant'],
        'Sanitation and Waster Supervisor': ['view_tenant'],
        'Recruitment Manager': ['view_tenant'],
        'Content Creator': ['view_tenant'],
        'Digital Platform and Community Cordinator': ['view_tenant'],
        'Security and Bio-exclusion Officer': ['view_tenant'],
        'Decollation Officer': ['view_tenant'],
        'Security and Bio-exclusion Officer': ['view_tenant'],
        'Receptionist': ['view_tenant'],
        'Ground and Greenery Keeper': ['view_tenant'],
        'Playground and Leisure Supervisor': ['view_tenant'],
        'Lead Ground and Greenery Keeper': ['view_tenant'],
        'Lead Playground and Leisure Supervisor': ['view_tenant'],
        'Senior Maintainance Engineer': ['view_tenant'],
        'Maintainance Engineer': ['view_tenant'],
        'Housing and Apartment Manager': ['add_tenant', 'view_tenant', 'change_tenant'],
        'Lead Housing and Apartment Manager': ['add_tenant', 'view_tenant', 'change_tenant', 'delete_tenant'],
        'Sales Agent': ['view_tenant'],
        'Marketing Manager': ['view_tenant'],
        'Derivery and Sales Agent': ['view_tenant'],
        'Packaging Manager': ['view_tenant'],
        'Processing Plant Supervisor': ['view_tenant'],
        'Senior Chef': ['view_tenant'],
        'Chef': ['view_tenant'],
        'Flock and Shed Attendant': ['view_tenant'],
        'Incubation and Hatchery Specialist': ['view_tenant'],
        'Customer': ['view_tenant'],
        'Nutritionist': ['view_tenant'],
        'Lead Nutritionist': ['view_tenant'],
        'Veterinary Officer': ['view_tenant'],
        'Lead Veterinary Officer': ['view_tenant'],
        'General Farm Manager': ['view_tenant'],
        'Farm Manager': ['view_tenant'],
        'Treasurer': ['view_tenant'],
        'Tenant': ['view_tenant'],
    },
    'LeaseAgreement': {
        'Chief Executive Officer': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement', 'delete_lease_agreement'],
        'System Administrator': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement', 'delete_lease_agreement'],
        'Human Resource Officer': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement'],
        'Human Resource Manager': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement'],
        'Lead Sanitation and Waster Supervisor': ['view_lease_agreement'],
        'Sanitation and Waster Supervisor': ['view_lease_agreement'],
        'Recruitment Manager': ['view_lease_agreement'],
        'Security and Bio-exclusion Officer': ['view_lease_agreement'],
        'Senior Maintainance Engineer': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement'],
        'Maintainance Engineer': ['view_lease_agreement'],
        'Housing and Apartment Manager': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement'],
        'Lead Housing and Apartment Manager': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement'],
        'Treasurer': ['view_lease_agreement'],
        'Tenant': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement'],
    },
    'RentInvoice': {
        'Chief Executive Officer': ['add_rental_invoice', 'view_rental_invoice', 'change_rental_invoice', 'delete_rental_invoice'],
        'System Administrator': ['add_rental_invoice', 'view_rental_invoice', 'change_rental_invoice', 'delete_rental_invoice'],
        'Housing and Apartment Manager': ['view_rental_invoice'],
        'Lead Housing and Apartment Manager': ['view_rental_invoice'],
        'Treasurer': ['view_rental_invoice'],
        'Tenant': ['add_rental_invoice', 'view_rental_invoice'],
    },
    'MaintenanceRequest': {
        'Chief Executive Officer': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement', 'delete_lease_agreement'],
        'System Administrator': ['add_lease_agreement', 'view_lease_agreement', 'change_lease_agreement', 'delete_lease_agreement'],
        'Lead Sanitation and Waster Supervisor': ['add_maintenance_request', 'view_maintenance_request', 'change_maintenance_request'],
        'Sanitation and Waster Supervisor': ['view_lease_agreement', 'change_maintenance_request'],
        'Senior Maintainance Engineer': ['view_maintenance_request', 'change_maintenance_request'],
        'Maintainance Engineer': ['view_maintenance_request', 'change_maintenance_request'],
        'Housing and Apartment Manager': ['add_maintenance_request', 'view_maintenance_request', 'change_maintenance_request', 'delete_maintenance_request'],
        'Lead Housing and Apartment Manager': ['add_maintenance_request', 'view_maintenance_request', 'change_maintenance_request', 'delete_maintenance_request'],
        'Ground and Greenery Keeper': ['add_maintenance_request', 'view_maintenance_request', 'change_maintenance_request', 'delete_maintenance_request'],
        'Receptionist': ['add_maintenance_request', 'view_maintenance_request', 'change_maintenance_request', 'delete_maintenance_request'],
        'Tenant': ['add_maintenance_request', 'view_maintenance_request', 'change_maintenance_request', 'delete_maintenance_request'],
    },
    'MaintenanceLog': {
        'Chief Executive Officer': ['add_maintenance_log', 'view_maintenance_log', 'change_maintenance_log', 'delete_maintenance_log'],
        'System Administrator': ['add_maintenance_log', 'view_maintenance_log', 'change_maintenance_log', 'delete_maintenance_log'],
        'Lead Sanitation and Waster Supervisor': ['view_maintenance_log'],
        'Sanitation and Waster Supervisor': ['view_maintenance_log'],
        'Senior Maintainance Engineer': ['add_maintenance_log', 'view_maintenance_log', 'change_maintenance_log', 'delete_maintenance_log'],
        'Maintainance Engineer': ['add_maintenance_log', 'view_maintenance_log', 'change_maintenance_log', 'delete_maintenance_log'],
        'Housing and Apartment Manager': ['view_maintenance_log'],
        'Lead Housing and Apartment Manager': ['view_maintenance_log'],
        'Receptionist': ['view_maintenance_log'],
        'Ground and Greenery Keeper': ['view_maintenance_log'],
        'Tenant': ['view_maintenance_log'],
    },
    'JobOpening': {
        'Chief Executive Officer': ['add_job_opening', 'change_job_opening', 'delete_job_opening', 'view_job_opening'],
        'Recruitment Manager': ['add_job_opening', 'change_job_opening', 'delete_job_opening', 'view_job_opening'],
        'Human Resource Officer': ['view_job_opening'],
        'Human Resource Manager': ['view_job_opening'],
        'Farm Manager': ['view_job_opening'],
        'Customer': ['view_job_opening'],
        'Applicant': ['view_job_opening'],
    },
    'ApplicantProfile': {
        'Chief Executive Officer': ['add_applicant_profile', 'change_applicant_profile', 'delete_applicant_profile', 'view_applicant_profile'],
        'Applicant': ['add_applicant_profile', 'view_applicant_profile', 'change_applicant_profile'],
        'Recruitment Manager': ['view_applicant_profile'],
    },
    'JobApplication': {
        'Chief Executive Officer': ['add_job_application', 'change_job_application', 'delete_job_application', 'view_job_application'],
        'Applicant': ['add_job_application', 'view_applicant_profile'],
        'Recruitment Manager': ['view_job_application'],
    },
    'Interview': {
        'Chief Executive Officer': ['add_interview', 'change_interview', 'delete_interview', 'view_interview'],
        'Applicant': ['view_interview'],
        'Recruitment Manager': ['add_interview', 'change_interview', 'delete_interview', 'view_interview'],
    },
    'Department': {
        'Chief Executive Officer': ['add_department', 'change_department', 'delete_department', 'view_department'],
        'Human Resource Manager': ['add_department', 'view_department'],
        'System Administrator': ['add_department', 'view_department'],
        'Lead Transport Officer': ['add_department', 'view_department'],
        'Lead Sanitation and Waster Supervisor': ['add_department', 'view_department'],
        'Lead Ground and Greenery Keeper': ['add_department', 'view_department'],
        'Lead Playground and Leisure Supervisor': ['add_department', 'view_department'],
        'Senior Maintainance Engineer': ['add_department', 'view_department'],
        'Lead Housing and Apartment Manager': ['add_department', 'view_department'],
        'Senior Chef': ['add_department', 'view_department'],
        'Lead Nutritionist': ['add_department', 'view_department'],
        'Lead Veterinary Officer': ['add_department', 'view_department'],
        'General Farm Manager': ['add_department', 'view_department'],
        'Farm Manager': ['add_department', 'view_department'],
    },
    'Employee': {
        'Chief Executive Officer': ['add_employee', 'change_employee', 'delete_employee', 'view_employee', 'can_deactivate_employee', 'can_change_employee_department', 'can_change_employee_type', 'can_assign_shed', 'can_change_shed', 'can_assign_plant', 'can_change_plant'],
        'Human Resource Manager': ['add_employee', 'view_employee', 'change_employee', 'can_deactivate_employee', 'can_change_employee_department', 'can_change_employee_type', 'can_assign_shed', 'can_change_shed', 'can_assign_plant', 'can_change_plant'],
        'Human Resource Officer': ['add_employee', 'view_employee', 'change_employee', 'can_assign_shed', 'can_assign_plant', 'can_change_plant'],
        'System Administrator': ['add_employee', 'change_employee', 'delete_employee', 'view_employee', 'can_deactivate_employee', 'can_change_employee_department', 'can_change_employee_type', 'can_assign_shed', 'can_change_shed', 'can_assign_plant', 'can_change_plant'],
        'Lead Transport Officer': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'Recruitment Manager': ['add_employee', 'view_employee', 'change_employee', 'can_change_employee_department', 'can_change_plant'],
        'Lead Sanitation and Waster Supervisor': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'Lead Ground and Greenery Keeper': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'Lead Playground and Leisure Supervisor': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'Senior Maintainance Engineer': ['view_employee', 'change_employee', 'can_change_employee_department', 'can_assign_plant', 'can_change_plant'],
        'Lead Housing and Apartment Manager': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'Senior Chef': ['view_employee', 'change_employee', 'can_change_employee_department', 'can_assign_plant', 'can_change_plant'],
        'Lead Nutritionist': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'Lead Veterinary Officer': ['view_employee', 'change_employee', 'can_change_employee_department'],
        'General Farm Manager': ['view_employee', 'change_employee', 'can_change_employee_department', 'can_assign_shed', 'can_change_shed', 'can_assign_plant', 'can_change_plant'],
        'Farm Manager': ['view_employee', 'change_employee', 'can_change_employee_department', 'can_assign_shed', 'can_change_shed', 'can_assign_plant', 'can_change_plant'],
    },
    'Employee': {
        'Chief Executive Officer': ['add_employee', 'change_employee', 'delete_employee', 'view_employee'],
        'Human Resource Manager': ['add_employee', 'change_employee', 'view_employee'],
        'Human Resource Officer': ['view_employee', 'change_employee'],
        'Recruitment Manager': ['view_employee', 'change_employee'],
    },
    'Farm': {
        'Chief Executive Officer': ['add_farm', 'change_farm', 'delete_farm', 'view_farm'],
        'Farm Manager': ['view_farm', 'change_farm'],
    }
}
