# Generated by Django 6.0.2 on 2026-03-22 12:35

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0002_managerhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmShed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Shed Name")),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Max Capacity (Birds)"),
                ),
                (
                    "shed_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Shed Specifications"
                    ),
                ),
                (
                    "last_empty_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the previous batch was cleared. Used to ensure a 14-day bio-security break.",
                        null=True,
                        verbose_name="Last Date Empty",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheds",
                        to="sfap.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Shed",
                "db_table": "shed",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["shed_metadata"], name="shed_spec_gin_idx"
                    )
                ],
                "unique_together": {("farm", "name")},
            },
        ),
    ]
