# Generated by Django 6.0.2 on 2026-03-22 13:01

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0003_farmshed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Batch ID",
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("BROILER", "Broiler"),
                            ("LAYER", "Layer"),
                            ("KUCHI", "Kuchi"),
                            ("LOCAL", "Local"),
                        ],
                        max_length=20,
                        verbose_name="Bird Type",
                    ),
                ),
                (
                    "initial_count",
                    models.PositiveIntegerField(verbose_name="Initial Bird Count"),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(verbose_name="Current Bird Count"),
                ),
                (
                    "expected_depletion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Depletion"
                    ),
                ),
                (
                    "batch_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Batch Details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEPLETED", "Depleted"),
                            ("QUARANTINED", "Quarantined"),
                            ("PROCESSING", "In Processing Plant"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sfap.farmshed",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch",
                "verbose_name_plural": "Flock Batches",
                "db_table": "batch",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["batch_details"], name="batch_details_gin_idx"
                    )
                ],
            },
        ),
    ]
