# Generated by Django 6.0.2 on 2026-03-22 13:06

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_employee_assigned_plant_employee_assigned_shed"),
        ("sfap", "0006_breederflock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="breederflock",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="breederflock",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="dailyobservation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="dailyobservation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="farmshed",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="farmshed",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="managerhistory",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="managerhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to="hrms.employee",
            ),
        ),
        migrations.CreateModel(
            name="Incubator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Incubator features"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Total number of eggs this machine can hold.",
                        verbose_name="Max Egg Capacity",
                    ),
                ),
                (
                    "last_sanitized",
                    models.DateTimeField(
                        blank=True,
                        help_text="Tracks bio-security/cleaning dates between cycles.",
                        null=True,
                        verbose_name="Last Sanitization Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "incubator",
                "db_table": "incubator",
            },
        ),
        migrations.CreateModel(
            name="IncubationCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "cycle_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Cycle ID",
                    ),
                ),
                (
                    "eggs_set_count",
                    models.PositiveIntegerField(verbose_name="Total Eggs Set"),
                ),
                (
                    "expected_hatch_date",
                    models.DateTimeField(verbose_name="Expected Hatch Date"),
                ),
                (
                    "incubation_logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic logs for candling results, machine temps, and embryo health.",
                        verbose_name="Incubation & Candling Logs",
                    ),
                ),
                ("actual_hatch_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SETTING", "Setting"),
                            ("CANDLING", "Candling"),
                            ("HATCHED", "Hatched"),
                            ("FAILED", "Failed"),
                        ],
                        default="SETTING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "breeder_flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incubation_cycles",
                        to="sfap.breederflock",
                        verbose_name="Breeder Flock",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
                (
                    "hatcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hatching_cycles",
                        to="sfap.incubator",
                        verbose_name="Incubator Machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incubation Cycle",
                "db_table": "incubation_cycle",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="HatchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                ("is_added_to_inventory", models.BooleanField(default=False)),
                (
                    "total_chicks_hatched",
                    models.PositiveIntegerField(verbose_name="Total Chicks Hatched"),
                ),
                (
                    "grade_a_chicks",
                    models.PositiveIntegerField(verbose_name="Grade A Chicks"),
                ),
                (
                    "grade_b_chicks",
                    models.PositiveIntegerField(verbose_name="Grade B Chicks"),
                ),
                (
                    "grade_c_chicks",
                    models.PositiveIntegerField(verbose_name="Grade C Chicks"),
                ),
                (
                    "quality_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed health data, weights, and vaccination records.",
                        verbose_name="Quality Metrics",
                    ),
                ),
                (
                    "hatchability_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Hatchability (%)",
                    ),
                ),
                (
                    "cull_weight_total",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Tracks the weight of rejected chicks for waste management.",
                        max_digits=10,
                        verbose_name="Total Cull Weight (KG)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "destination_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The production batch these chicks were moved to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfap.batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
                (
                    "incubation_cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatch_record",
                        to="sfap.incubationcycle",
                        verbose_name="Incubation Cycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatch Record",
                "db_table": "hatch_record",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["quality_metrics"], name="hatch_quality_gin_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="incubator",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["features"], name="incubator_features_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incubationcycle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["incubation_logs"], name="incubation_log_gin_idx"
            ),
        ),
    ]
