# Generated by Django 6.0.2 on 2026-03-22 13:14

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_employee_assigned_plant_employee_assigned_shed"),
        ("sfap", "0008_farmvehicle_transportmovement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseOutbreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "suspected_disease",
                    models.CharField(
                        max_length=255, verbose_name="Suspected Disease/Condition"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "diagnostic_data",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed symptoms, lab results, and containment measures.",
                        verbose_name="Diagnostic & Quarantine Data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Outbreak"),
                            ("CONTAINED", "Contained/Under Treatment"),
                            ("RESOLVED", "Resolved/Closed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Incident Status",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sfap.batch",
                        verbose_name="Impacted Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Outbreak",
                "db_table": "disease_outbreak",
                "ordering": ["-created_on"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["diagnostic_data"], name="outbreak_diag_gin_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Protocol Name"),
                ),
                (
                    "target_bird_type",
                    models.CharField(
                        choices=[
                            ("BROILER", "Broiler"),
                            ("LAYER", "Layer"),
                            ("KUCHI", "Kuchi"),
                            ("LOCAL", "Local"),
                        ],
                        max_length=50,
                        verbose_name="Target Bird Type",
                    ),
                ),
                (
                    "protocol_steps",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of scheduled health tasks by bird age (days).",
                        verbose_name="Protocol Steps",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Detailed Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Protocol",
                "verbose_name_plural": "Health Protocols",
                "db_table": "health_protocol",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["protocol_steps"], name="health_protocol_gin_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, verbose_name="Date of Administration"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("VACCINATION", "Vaccination"),
                            ("MEDICATION", "Medication/Treatment"),
                            ("PROCEDURE", "General Procedure (e.g., De-beaking)"),
                            ("LAB_RESULT", "Laboratory Test Result"),
                        ],
                        max_length=20,
                        verbose_name="Record Type",
                    ),
                ),
                (
                    "event_details",
                    models.JSONField(
                        default=dict,
                        help_text="Stores item names, batch numbers, and administration methods.",
                        verbose_name="Event Details",
                    ),
                ),
                (
                    "cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("KES", "Kenyan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                            ("USD", "US Dollar"),
                        ],
                        default="TZS",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=djmoney.money.Money(0.0, "TZS"),
                        max_digits=14,
                        verbose_name="Total Cost",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Clinical Notes")),
                ("withdrawal_end_date", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="sfap.batch",
                        verbose_name="Flock Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to="hrms.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "db_table": "medical_record",
                "ordering": ["-date"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["event_details"], name="medical_event_gin_idx"
                    )
                ],
            },
        ),
    ]
