# Generated by Django 6.0.2 on 2026-03-22 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0009_diseaseoutbreak_healthprotocol_medicalrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
