# Generated by Django 6.0.2 on 2026-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0010_alter_farm_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managerhistory",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="managerhistory",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="managerhistory",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="managerhistory",
            name="updated_on",
        ),
    ]
