# Generated by Django 6.0.2 on 2026-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0011_remove_managerhistory_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={
                "permissions": [
                    ("add_daily_observation", "Can add daily observation"),
                    ("log_mortality", "Can log mortality"),
                    ("update_water_intake", "Can update water intake"),
                    ("log_egg_collection", "Can log egg collection"),
                    ("approve_batch_movement", "Can approve batch movement"),
                    ("view_kpi_dashboard", "Can view KPI dashboard"),
                    ("assign_shed_worker", "Can assign shed worker"),
                    ("manage_biosecurity_lockdown", "Can manage biosecurity lockdown"),
                    ("manage_incubation_cycle", "Can manage incubation cycle"),
                    ("log_hatch_results", "Can log hatch results"),
                    ("update_breeder_traits", "Can update breeder traits"),
                    ("check_egg_fertility", "Can check egg fertility"),
                    ("prescribe_medication", "Can prescribe medication"),
                    ("log_vaccination", "Can log vaccination"),
                    ("declare_disease_outbreak", "Can declare disease outbreak"),
                    ("issue_health_clearance", "Can issue health clearance"),
                ],
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
            },
        ),
    ]
