# Generated by Django 6.0.2 on 2026-04-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0013_alter_batch_created_by_alter_batch_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={"verbose_name": "Farm", "verbose_name_plural": "Farms"},
        ),
    ]
