# Generated by Django 6.0.2 on 2026-04-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0014_alter_farm_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmshed",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sheds",
                to="sfap.farm",
            ),
        ),
    ]
