# Generated by Django 6.0.2 on 2026-04-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0015_alter_farmshed_farm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={
                "ordering": ["-date_of_administration"],
                "verbose_name": "Medical Record",
            },
        ),
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="date",
            new_name="date_of_administration",
        ),
    ]
