# Generated by Django 6.0.2 on 2026-04-13 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0016_alter_medicalrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="date_of_administration",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date of Administration",
            ),
        ),
    ]
