# Generated by Django 6.0.2 on 2026-04-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sfap", "0017_alter_medicalrecord_date_of_administration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={
                "ordering": ["-id"],
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
            },
        ),
    ]
