# Generated by Django 6.0.2 on 2026-05-17 07:19

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingPlant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        db_index=True, null=True, verbose_name="Updated On"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Plant Name"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Location Details"),
                ),
                (
                    "plant_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Plant Configuration"
                    ),
                ),
                (
                    "certification_info",
                    models.JSONField(
                        default=dict,
                        help_text="Stores Halal status, health permits, and inspection records.",
                        verbose_name="Certification & Permits",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant_manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_plants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Plant Manager",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Plant",
                "db_table": "processing_plant",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["plant_config"], name="plant_config_gin_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["certification_info"], name="plant_cert_gin_idx"
                    ),
                ],
            },
        ),
    ]
