# Generated by Django 6.0.2 on 2026-06-20 20:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "birds_processed",
                    models.PositiveIntegerField(verbose_name="Birds Processed"),
                ),
                (
                    "live_birds_count",
                    models.PositiveIntegerField(verbose_name="Live Birds Input"),
                ),
                (
                    "total_live_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Live Weight (KG)"
                    ),
                ),
                (
                    "total_dressed_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Dressed Weight (KG)",
                    ),
                ),
                (
                    "slaughter_data",
                    models.JSONField(default=dict, verbose_name="Slaughter Metrics"),
                ),
                (
                    "environmental_logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Audit trail for water temperature, voltage, and safety metrics.",
                        verbose_name="Processing Parameters",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Session Start")),
                ("end_time", models.DateTimeField(verbose_name="Session End")),
                (
                    "yield_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Yield Percentage (%)",
                    ),
                ),
                (
                    "temperature_recorder",
                    models.CharField(
                        max_length=100, verbose_name="Temperature Recorded"
                    ),
                ),
                (
                    "rejected_birds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Birds rejected during inspection for health/quality reasons.",
                        verbose_name="Rejects/Condemned",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Session",
                "db_table": "processing_session",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingPlant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Plant Name"
                    ),
                ),
                (
                    "plant_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Plant Configuration"
                    ),
                ),
                (
                    "certification_info",
                    models.JSONField(
                        default=dict,
                        help_text="Stores Halal status, health permits, and inspection records.",
                        verbose_name="Certification & Permits",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Plant",
                "db_table": "processing_plant",
            },
        ),
    ]
