# Generated by Django 6.0.2 on 2026-06-13 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingplant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="processingplant",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Updated On"
            ),
        ),
    ]
