# Generated by Django 6.0.2 on 2026-06-20 20:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hrms", "0001_initial"),
        ("ppms", "0001_initial"),
        ("sfap", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processingplant",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="locations",
                to="sfap.farm",
                verbose_name="Farm to which a plant is",
            ),
        ),
        migrations.AddField(
            model_name="processingplant",
            name="plant_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_plants",
                to="hrms.employee",
                verbose_name="Plant Manager",
            ),
        ),
        migrations.AddField(
            model_name="processingplant",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="assigned_workers",
            field=models.ManyToManyField(
                blank=True,
                related_name="session_workers",
                to="hrms.employee",
                verbose_name="Assigned Staff",
            ),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="ppms.processingplant",
            ),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="source_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_runs",
                to="sfap.batch",
                verbose_name="Source Batch",
            ),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(app_label)s_%(class)s_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="processingplant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["plant_config"], name="plant_config_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingplant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["certification_info"], name="plant_cert_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingsession",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["environmental_logs"], name="environmental_logs_gin_idx"
            ),
        ),
    ]
