# Generated by Django 6.0.2 on 2026-06-17 20:03

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0004_alter_department_created_by_and_more"),
        ("ppms", "0002_alter_processingplant_created_by_and_more"),
        ("sfap", "0010_incubator_incubationcycle_hatchrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "birds_processed",
                    models.PositiveIntegerField(verbose_name="Birds Processed"),
                ),
                (
                    "live_birds_count",
                    models.PositiveIntegerField(verbose_name="Live Birds Input"),
                ),
                (
                    "total_live_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Live Weight (KG)"
                    ),
                ),
                (
                    "total_dressed_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Dressed Weight (KG)",
                    ),
                ),
                (
                    "slaughter_data",
                    models.JSONField(default=dict, verbose_name="Slaughter Metrics"),
                ),
                (
                    "environmental_logs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Audit trail for water temperature, voltage, and safety metrics.",
                        verbose_name="Processing Parameters",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Session Start")),
                ("end_time", models.DateTimeField(verbose_name="Session End")),
                (
                    "yield_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Yield Percentage (%)",
                    ),
                ),
                (
                    "temperature_recorder",
                    models.CharField(
                        max_length=100, verbose_name="Temperature Recorded"
                    ),
                ),
                (
                    "rejected_birds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Birds rejected during inspection for health/quality reasons.",
                        verbose_name="Rejects/Condemned",
                    ),
                ),
                (
                    "assigned_workers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="session_workers",
                        to="hrms.employee",
                        verbose_name="Assigned Staff",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="ppms.processingplant",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_runs",
                        to="sfap.batch",
                        verbose_name="Source Batch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Session",
                "db_table": "processing_session",
                "ordering": ["-start_time"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["environmental_logs"], name="environmental_logs_gin_idx"
                    )
                ],
            },
        ),
    ]
